### ISSUE TITLE
unpack_assessment_zip managment command fails on windows

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3347]
Using the installer built from `ka-lite-installer-windows` on the branch `master`, I tried both starting the server for the first time and running the command `bin/windows/kalite.bat start`. The first fails quietly, while the latter has the following error:
```cmd
Traceback (most recent call last):
  File "python-packages\django\core\management\base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "python-packages\django\core\management\base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "C:\Program Files\KA Lite4\ka-lite\kalite\contentload\management\commands\unpack_assessment_zip.py", line 58, in handle
    f = tempfile.TemporaryFile("r+w")
  File "C:\Python27\lib\tempfile.py", line 455, in NamedTemporaryFile
    file = _os.fdopen(fd, mode, bufsize)
ValueError: Invalid mode ('r+w')
```

@aronasorman seems like "r+w" [isn't truly a valid mode](https://docs.python.org/2/library/functions.html#open), but works ok enough in linux. Maybe the desired mode is "r+"?

**Comment by aronasorman** [comment]
Ah, indeed you are correct. I can open a PR later this afternoon, if it's not urgent.
