### ISSUE TITLE
Outdated language pack generates an exception during start.

### ISSUE THREAD

**Issue by cpauya** [learningequality/ka-lite#3361]
**Branch** **develop**
**Target** **for 0.13.x**

**Expected Behavior**  When `bin/kalite start` is run, it should detect if the current language pack (and .json files) are valid and inform the user to update the language packs.

**Current Behavior**  When `bin/kalite start` is run, it generates this exception on the command line:

```bash
$ bin/kalite start
...
DEBUG:kalite:choosing best language among set(['en'])
DEBUG:kalite:choosing best language among set(['en'])
INFO:kalite:Preloading content data for language en.
...
DEBUG:kalite:Adding dubbed video map entry for None (name=my)
DEBUG:kalite:Adding dubbed video map entry for None (name=pl)
AttributeError: 'NoneType' object has no attribute 'iteritems'
...
```

**To Reproduce**

Use an outdated/invalid `/kalite/i18n/data/dubbed_video_mappings.json` then run `bin/kalite start` and notice the error above.  Here's an example `dubbed_video_mappings.json` dating back Jan-09-2015:

```json
{
    "ar": null,
    "bg": null,
    "da": null,
    "de": null,
    "en": null,
    "es": {
        "crowdin": "es-ES"
    },
    "fr": null,
    "my": {
        "beta": true
    },
    "pl": null,
    "lo": null,
    "pt-BR": {
        "dubbed_videos": "pt"
    },
    "xh": {
        "beta": true
    }
}
```

**Possible Solution/s**

1. Check your `local_settings.py` has `CENTRAL_SERVER_HOST = "staging.learningequality.org"`.

    1. Update your language pack/s with `python manage.py languagepackdownload -l de --commandline` -- this will update the German language pack.  Or remove the `-l de` so it updates all language packs.

1. Code to check validity of language pack and it's .json files.

**Comment by cpauya** [comment]
Here's the traceback of the exception using `python manage.py runserver --traceback`

```bash
DEBUG:kalite:Adding dubbed video map entry for None (name=pl)
Traceback (most recent call last):
  File "./python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "./python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/distributed/management/commands/kaserve.py", line 127, in handle
    self.reinitialize_server()
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/distributed/management/commands/kaserve.py", line 97, in reinitialize_server
    initialize_content_caches()
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/caching/__init__.py", line 108, in initialize_content_caches
    topic_tools.get_content_cache(force=force, annotate=True, language=lang)
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/topic_tools/__init__.py", line 256, in get_content_cache
    dubmap = i18n.get_id2oklang_map(content.get("id"))
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/i18n/__init__.py", line 148, in get_id2oklang_map
    for english_youtube_id, dubbed_youtube_id in dic.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'
```
