### ISSUE TITLE
Some assessment item API endpoints returning Status 500 errors

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3413]
In 0.13 alpha (pre-release) discovered several assessment items that were missing the graphical elements they seemed to rely. Jamie recently became aware of an issue with the way SVG data is being handled within the offical Khan API which may be related and lead to solutions to this particular assessment item and other other assessment items similarly affected . 

All that said the particular issue can be reproduced by attempting to run the Light Puzzle 1 assessment item. Screen shots attached. There seems to be a missing but continually changing url needed which can be seen referenced via the chrome inspection tool in the second screen shot. This same issue appears to be reproduced in all the light puzzle assessment items, transformation puzzles assessment items, and recreational maps, under the math assessments. 
![capture119](https://cloud.githubusercontent.com/assets/4349806/6855542/e8274b36-d3be-11e4-9311-e3fea66d3b72.PNG)
![capture117](https://cloud.githubusercontent.com/assets/4349806/6855546/efdbafe8-d3be-11e4-8fcf-0076e1fd03fb.PNG)

**Comment by jamalex** [comment]
Hmm, that looks like a different issue -- it's returning 500s on the API endpoints. Might not have anything to do with images.

**Comment by jamalex** [comment]
Can you set `DEBUG = True` and inspect the response on that API endpoint?

**Comment by jamalex** [comment]
Also, that X in the top right is to clear the error message. But what happened to the color on the error message bubble?

**Comment by EdDixon** [comment]
Was trying to highlight that not sure why the x is there?

**Comment by rtibbles** [comment]
It's from the error message alert box.

**Comment by EdDixon** [comment]
I should also add this was while testing without internet availability.

**Comment by jamalex** [comment]
I went ahead and tested this out, with `DEBUG = True`. Here's the traceback:

```
Traceback (most recent call last):
File "ka-lite/python-packages/tastypie/resources.py", line 195, in wrapper response = callback(request, *args, **kwargs)
File "ka-lite/python-packages/tastypie/resources.py", line 435, in dispatch_detail return self.dispatch('detail', request, **kwargs)
File "ka-lite/python-packages/tastypie/resources.py", line 458, in dispatch response = method(request, **kwargs)
File "ka-lite/python-packages/tastypie/resources.py", line 1295, in get_detail obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs))
File "ka-lite/python-packages/tastypie/resources.py", line 1113, in cached_obj_get cached_bundle = self.obj_get(bundle=bundle, **kwargs)
File "ka-lite/kalite/main/api_resources.py", line 209, in obj_get assessment_item = get_assessment_item_data(bundle.request, assessment_item_id)
File "ka-lite/kalite/topic_tools/__init__.py", line 502, in get_assessment_item_data item_data = smart_translate_item_data(item_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 525, in smart_translate_item_data item_data[field] = smart_translate_item_data(field_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 525, in smart_translate_item_data item_data[field] = smart_translate_item_data(field_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 525, in smart_translate_item_data item_data[field] = smart_translate_item_data(field_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 525, in smart_translate_item_data item_data[field] = smart_translate_item_data(field_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 527, in smart_translate_item_data item_data[field] = map(smart_translate_item_data, field_data)
File "ka-lite/kalite/topic_tools/__init__.py", line 523, in smart_translate_item_data for field, field_data in item_data.iteritems(): AttributeError: 'str' object has no attribute 'iteritems'
```

**Comment by jamalex** [comment]
Looks like @aronasorman touched that code (or rather, wrote it from scratch) most recently. Could you look into this?

Here's the endpoint I tried: http://127.0.0.1:8008/api/assessment_item/x94f5e2f8003b5694/

**Comment by rtibbles** [comment]
In this case, it seems that the 'widgets' key on the question object is being translated for some reason.

**Comment by rtibbles** [comment]
Problem arises from not checking that 'item_data' is a dict. Fixing now.

**Comment by aronasorman** [comment]
Fixed in PRs above ^
