### ISSUE TITLE
runserver fails on 0.13.x

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3581]
On `0.13.x`, the following command:
```sh
python kalitectl.py manage runserver
```

Results in:

```sh
Traceback (most recent call last):
  File "/home/vagrant/ka-lite/kalitectl.py", line 504, in <module>
    args=arguments['DJANGO_OPTIONS']
  File "/home/vagrant/ka-lite/kalitectl.py", line 353, in start
    '--pid-file={0000:s}'.format(PID_FILE_JOB_SCHEDULER)
  File "/home/vagrant/ka-lite/kalitectl.py", line 288, in manage
    get_commands()
  File "/home/vagrant/ka-lite/python-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/vagrant/ka-lite/python-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/home/vagrant/ka-lite/python-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/vagrant/ka-lite/python-packages/django/conf/__init__.py", line 134, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'kalite.settings' (Is it on sys.path?): cannot import name ROOT_DATA_PATH
```

**Comment by aronasorman** [comment]
You just have to clear your pyc fails. This happens after switching from develop to 0.13.x:

```shell
find . -name "*.pyc" -delete
```

**Comment by aronasorman** [comment]
This is because we don't clear the pyc files on startup now.

**Comment by MCGallaspy** [comment]
Bummer

**Comment by aronasorman** [comment]
I cannot into english today.
