### ISSUE TITLE
yaml library dependency breaks the installer

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3633]
https://travis-ci.org/learningequality/ka-lite/jobs/62159469#L194

```
$ pip install .
You are using pip version 6.0.7, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/travis/build/learningequality/ka-lite
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-IkASqx-build/setup.py", line 7, in <module>
        import kalite
      File "kalite/__init__.py", line 4, in <module>
        from version import *
      File "kalite/version.py", line 2, in <module>
        import yaml
    ImportError: No module named yaml
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-IkASqx-build/setup.py", line 7, in <module>
        import kalite
      File "kalite/__init__.py", line 4, in <module>
        from version import *
      File "kalite/version.py", line 2, in <module>
        import yaml
    ImportError: No module named yaml
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-IkASqx-build
The command "pip install ." failed and exited with 1 during .
Your build has been stopped.
```

So the problem, once again, is that `kalite.version` is a very very low-level file and should not be made too complicated :)

Suggest moving `import yaml` to `VERSION_INFO()`

Also, how is the yaml library distributed and what should be put in requirements.txt?

**Comment by benjaoming** [comment]
My bad, pyyaml was already added to requirements.txt
