### ISSUE TITLE
develop branch won't start the server if install does not get run before

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3640]
reproduce the error:
1. make sure to have a fresh clone of kalite develop branch
2. navigate the the dir and run $ python kalitectl.py start
then you will see the following error
```bash
Traceback (most recent call last):
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalitectl.py", line 553, in <module>
    args=arguments['DJANGO_OPTIONS']
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalitectl.py", line 415, in start
    manage('kaserve', args)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalitectl.py", line 337, in manage
    utility.execute()
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalite/settings/__init__.py", line 37, in <module>
    CHERRYPY_PORT = getattr(local_settings, "CHERRYPY_PORT", PRODUCTION_PORT)
NameError: name 'PRODUCTION_PORT' is not defined
Elis-MacBook-Pro:bin Eli$ Traceback (most recent call last):
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalitectl.py", line 583, in <module>
    manage(command, args=arguments['DJANGO_OPTIONS'])
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalitectl.py", line 337, in manage
    utility.execute()
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/Eli/Desktop/Kalite-sidebar-benchmark/kalite_develop/ka-lite/kalite/settings/__init__.py", line 37, in <module>
    CHERRYPY_PORT = getattr(local_settings, "CHERRYPY_PORT", PRODUCTION_PORT)
NameError: name 'PRODUCTION_PORT' is not defined

**Comment by benjaoming** [comment]
this typically happens when `kalite.distributed` wasn't listed in INSTALLED_APPS and thus part of the magically loaded `application.settings`..

**Comment by aronasorman** [comment]
@benjaoming you mean they have a custom-defined `INSTALLED_APPS` in their `local_settings`?

**Comment by benjaoming** [comment]
yeah, that used to be the problem, but that should actually be fixed unless somehow that wasn't merged or something... I'll have a look tomorrow.

**Comment by MCGallaspy** [comment]
I think this is resolved on `develop`, or at least I've had no issues with `kalite start`.
