### ISSUE TITLE
TransactionManagementError during tests

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3669]
This bug isn't critical, but it's pretty annoying for development. For an example, see #3636. The likely cause is that the sqlite DB is tied up by an API endpoint while the test suite continues. See [this bug report](https://code.djangoproject.com/ticket/20382). Here's the example from #3636:
```sh
Feature: UI regression tests # kalite/distributed/features/ui_regression.feature:1
  To ensure that basic functionality is not lost
  Scenario: Coach has a logout link          # kalite/distributed/features/ui_regression.feature:4
    Given I'm logged in as a coach           # kalite/distributed/features/steps/ui_regression.py:11
Given I'm logged in as a coach           # kalite/distributed/features/steps/ui_regression.py:11 0.696s
      Traceback (most recent call last):
        File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/travis/build/learningequality/ka-lite/kalite/distributed/features/steps/ui_regression.py", line 13, in step_impl
          login_as_coach(context)
        File "/home/travis/build/learningequality/ka-lite/kalite/testing/behave_helpers.py", line 245, in login_as_coach
          context_wm.create_teacher(username=coach_name, password=coach_pass)
        File "/home/travis/build/learningequality/ka-lite/kalite/testing/mixins/facility_mixins.py", line 71, in create_teacher
          return cls.create_student(**fields)  # delegate to the create_student method, which has the right logic
        File "/home/travis/build/learningequality/ka-lite/kalite/testing/mixins/facility_mixins.py", line 54, in create_student
          user.save()
        File "/home/travis/build/learningequality/ka-lite/kalite/facility/models.py", line 179, in save
          CachedPassword.invalidate_cached_password(user=self)
        File "/home/travis/build/learningequality/ka-lite/kalite/facility/models.py", line 283, in invalidate_cached_password
          cls.objects.filter(user=user).delete()
        File "./python-packages/django/db/models/query.py", line 537, in delete
          collector.delete()
        File "./python-packages/django/db/models/deletion.py", line 69, in decorated
          transaction.leave_transaction_management(using=self.using)
        File "./python-packages/django/db/transaction.py", line 66, in leave_transaction_management
          connection.leave_transaction_management()
        File "./python-packages/django/db/backends/__init__.py", line 131, in leave_transaction_management
          "This code isn't under transaction management")
      TransactionManagementError: This code isn't under transaction management
```

So what's the solution? Assuming that long-running API endpoints are the cause, perhaps we can kill those requests after each test.

**Comment by aronasorman** [comment]
I don't get this error during tests. @MCGallaspy if you still get this please reopen it.
