### ISSUE TITLE
AttributeError on Android

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3791]
Branch: develop
I use adb connect to an android device and run the line: python kalitectl.py start
I got AttributeError: 'Settings' object has no attribute 'I18N_DATA_PATH'

traceback:
```
/data/data/com.android.kalite27/files/kalite/settings/base.py:38: RemovedInKALite_v015_Warning: We will be deprecating the old way of statically importing custom settings, in favor of a more flexible way. The easiest way to update your installation is to rename your local_settings.py (keeping it in the same directory) and add an import statement in the very first line of the new file so it looks like this:

    from kalite.settings.base import *
    # Put custom settings here...
    FOO = BAR

and then call kalite start with an additional argument pointing to your new settings module:

    kalite start --settings=kalite.my_settings

In the future, it is recommended not to keep your own settings module in the kalite code base but to put the file somewhere else in your python path, for instance in the current directory when running 'kalite --settings=my_module'.
  RemovedInKALite_v015_Warning
/data/data/com.android.kalite27/files/kalite/settings/base.py:38: RemovedInKALite_v015_Warning: We will be deprecating the old way of statically importing custom settings, in favor of a more flexible way. The easiest way to update your installation is to rename your local_settings.py (keeping it in the same directory) and add an import statement in the very first line of the new file so it looks like this:

    from kalite.settings.base import *
    # Put custom settings here...
    FOO = BAR

and then call kalite start with an additional argument pointing to your new settings module:

    kalite start --settings=kalite.my_settings

In the future, it is recommended not to keep your own settings module in the kalite code base but to put the file somewhere else in your python path, for instance in the current directory when running 'kalite --settings=my_module'.
  RemovedInKALite_v015_Warning
Traceback (most recent call last):
  File "kalitectl.py", line 615, in <module>
    args=arguments['DJANGO_OPTIONS']
  File "kalitectl.py", line 422, in start
    manage('kaserve', args)
  File "kalitectl.py", line 344, in manage
    utility.execute()
  File "python-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "python-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "python-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/data/data/com.android.kalite27/files/kalite/distributed/management/commands/kaserve.py", line 17, in <module>
    from kalite.caching import initialize_content_caches
  File "/data/data/com.android.kalite27/files/kalite/caching/__init__.py", line 25, in <module>
    from kalite import i18n, topic_tools
  File "/data/data/com.android.kalite27/files/kalite/i18n/__init__.py", line 42, in <module>
    DUBBED_VIDEOS_MAPPING_FILEPATH = os.path.join(settings.I18N_DATA_PATH, "dubbed_video_mappings.json")
  File "python-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'I18N_DATA_PATH'
1|root@astar-inet:/data/data/com.android.kalite27/files # AttributeError: 'Settings' object has no attribute 'I18N_DATA_PATH'
```

**Comment by 66eli77** [comment]
@benjaoming  any insights on what could possibly cause this problem?

**Comment by benjaoming** [comment]
So this is another case this §/#¤"&"#)!# where we have two options:

1. Somehow the load order is different on your system
1. There is actually an exception when loading `kalite.settings` which has been silenced and instead `legacy.i18n_settings` simply wasn't loaded and included and the exception was thrown away (my guess).

If you look at how the said `I18N_DATA_PATH` is defined, you have the following which might be a sensitive aspect, so you could try running that from `kalite shell` and see if something breaks.

```python
from pkg_resources import resource_filename
I18N_DATA_PATH = resource_filename("kalite", "i18n/data")
LANG_LOOKUP_FILEPATH = os.path.join(I18N_DATA_PATH, "languagelookup.json")
```

**Comment by benjaoming** [comment]
And this is why I want to refactor settings.

**Comment by benjaoming** [comment]
Closing, because #4003 forces a change in `DUBBED_VIDEOS_MAPPING_FILEPATH` anyways.

So it's not necessarily fixed (although you could try again as load order could have shifted).. but it will be fixed.
