### ISSUE TITLE
Remove all paths based on __file__

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3862]
Branch: develop
Install method: `python setup.py install --static` within a virtualenv, on Ubuntu

I previously downloaded the EN language pack with no issue, and it worked. Now, I tried downloading the Spanish language pack, and got the following error:

![image](https://cloud.githubusercontent.com/assets/618416/8142139/d3f1330a-1128-11e5-86f7-2ebaa6682c09.png)

It looks like maybe it's trying to unpack or otherwise write something to the **file path** `/static` (i.e. using the URL path as a file path)?

**Comment by benjaoming** [comment]
Sorry I didn't get back on this, I will look at it in around 15 hours from now :)

**Comment by benjaoming** [comment]
Here's a full stack trace:

```
[Errno 13] Permission denied: '/static'


Traceback (most recent call last):

  File "/mnt/snowden-is-god/ka-lite/python-packages/fle_utils/chronograph/models.py", line 209, in run_management_command
    call_command(self.command, *args, **options)

  File "/mnt/snowden-is-god/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)

  File "/mnt/snowden-is-god/ka-lite/python-packages/fle_utils/django_utils/command.py", line 216, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)

  File "/mnt/snowden-is-god/ka-lite/python-packages/fle_utils/chronograph/management/croncommand.py", line 38, in execute
    super(CronCommand, self).execute(*args, **kwargs)

  File "/mnt/snowden-is-god/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)

  File "/mnt/snowden-is-god/ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 97, in handle
    move_exercises(lang_code)

  File "/mnt/snowden-is-god/ka-lite/kalite/updates/management/commands/languagepackdownload.py", line 175, in move_exercises
    ensure_dir(dest_exercise_dir)

  File "/mnt/snowden-is-god/ka-lite/python-packages/fle_utils/general.py", line 139, in ensure_dir
    os.makedirs(path)

  File "/mnt/snowden-is-god/ka-lite/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)

  File "/mnt/snowden-is-god/ka-lite/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)

  File "/mnt/snowden-is-god/ka-lite/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)

  File "/mnt/snowden-is-god/ka-lite/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)

  File "/mnt/snowden-is-god/ka-lite/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/static'
```

**Comment by benjaoming** [comment]
Seems to be a problem with this:

```python
def get_localized_exercise_dirpath(lang_code):
    ka_lang_code = lang_code.lower()
    return os.path.join(os.path.dirname(__file__), settings.KHAN_EXERCISES_RELPATH, "exercises", ka_lang_code)
```

...which contains the magic "__file__" that should be removed more generally speaking! :)

**Comment by benjaoming** [comment]
Btw this also fails on a git checkout run directly from source.

**Comment by benjaoming** [comment]
Oh dear

```
kalite/i18n/management/commands/i18nize_templates.py
116:                        (parse_file, app.__file__, ', '.join(extensions),))
121:        local_dir = os.path.dirname(app.__file__)

kalite/i18n/tests/create_dummy_language_pack_tests.py
25:        zf.write(__file__)      # write the current file into the zipfile, just so we have something in here

kalite/i18n/tests/base.py
22:        test_zip_filepath = os.path.join(os.path.dirname(__file__), 'testzips', '%s.zip' % lang_code)

kalite/i18n/__init__.py
51:    return os.path.join(os.path.dirname(__file__), settings.KHAN_EXERCISES_RELPATH, "exercises", ka_lang_code)
376:    output_dir = os.path.join(os.path.dirname(__file__), 'static', 'js', 'i18n')

kalite/project/wsgi.py
17:PROJECT_PATH = os.path.dirname(os.path.realpath(__file__))

kalite/ab_testing/management/commands/read_facility_conditions.py
37:        savedir = os.path.join(os.path.dirname(__file__),

kalite/ab_testing/data/groups.py
4:with open(os.path.join(os.path.dirname(__file__), "facility_unit_mappings.json")) as f:
7:with open(os.path.join(os.path.dirname(__file__), "facility_grade_mappings.json")) as f:

kalite/student_testing/settings.py
10:STUDENT_TESTING_DATA_PATH = os.path.join(os.path.dirname(__file__), "data")

kalite/static/admin/js/compress.py
7:here = os.path.dirname(__file__)

kalite/static/perseus/ke/build/kathjax.py
29:mjdir = os.path.abspath(os.path.join(os.path.dirname(__file__),
61:config_js = open(os.path.join(origwd, os.path.dirname(__file__),
105:khan_exercise_path = os.path.join(origwd, os.path.dirname(__file__),

kalite/static/perseus/ke/build/lint_i18n_strings_test.py
101:        os.chdir(os.path.dirname(os.path.realpath(__file__)))

kalite/static/perseus/ke/tools/runlint.py
16:_CWD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

kalite/contentload/tests/unpack_assessment_zip.py
21:TEMP_ASSESSMENT_ITEM_JSON_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "assessmentitems.json")
22:DUMMY_ASSESSMENT_ITEM_DATABASE_SOURCE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "assessmentitems.dummydb")

kalite/contentload/tests/generate_assessment_zips.py
20:TEST_FIXTURES_DIR = os.path.join(os.path.dirname(__file__),

kalite/store/management/commands/convert_xls_to_items.py
49:            os.path.dirname(__file__),

kalite/playlist/management/commands/add_new_playlists.py
23:            os.path.dirname(__file__),

kalite/playlist/models.py
92:    playlistjson = os.path.join(os.path.dirname(__file__), 'playlists.json')

kalite/basetests/tests.py
5:THIS_PATH = os.path.dirname(os.path.realpath(__file__))

kalite/testing/testrunner.py
20:    app_dir = os.path.dirname(app_module.__file__)

kalite/distributed/static/perseus/ke/build/kathjax.py
29:mjdir = os.path.abspath(os.path.join(os.path.dirname(__file__),
61:config_js = open(os.path.join(origwd, os.path.dirname(__file__),
105:khan_exercise_path = os.path.join(origwd, os.path.dirname(__file__),

kalite/distributed/static/perseus/ke/build/lint_i18n_strings_test.py
101:        os.chdir(os.path.dirname(os.path.realpath(__file__)))

kalite/distributed/static/perseus/ke/tools/runlint.py
16:_CWD = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

kalite/distributed/tests/browser_tests/language_packs.py
38:        test_zip_filepath = os.path.join(os.path.dirname(__file__), 'de.zip')

kalite/distributed/tests/browser_tests/control_panel.py
125:        test_zip_filepath = os.path.join(os.path.dirname(__file__), 'es.zip')

kalite/distributed/settings.py
42:TEMPLATE_DIRS = (os.path.join(os.path.dirname(__file__), "templates"),)

kalite/settings/base.py
86:    os.path.split(os.path.dirname(os.path.realpath(__file__)))[0]
104:    _data_path = os.path.realpath(os.path.join(os.path.dirname(__file__), "..", ".."))

kalite/settings/__init__.py
126:SCREENSHOTS_JSON_PATH = os.path.join(os.path.dirname(__file__), "data")

kalite/main/tests/fixture_tests.py
17:        cur_dir = os.path.split(__file__)[0]
```

**Comment by MCGallaspy** [comment]
Stealing this @benjaoming.

**Comment by jamalex** [comment]
The specific error I'm fixing/tracking here: https://github.com/learningequality/ka-lite/issues/3919
