### ISSUE TITLE
testing application problems

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#3875]
So two issues:

 1. We should put a models.py in `fle_utils.testing` if it's supposed to be used -- or just remove the thing
 1. Make a decision about "_built.touch" because I don't see where this thing is even created, so we can get rid of `kalite.settings.BUILT` all-together and clean up the logic of that.

Currently, stuff is breaking because of having enabled `fle_utils.testing` which was a consequence of when I tried cleaning up settings modules of all applications.

**Comment by benjaoming** [comment]
`fle_utils.testing` seems to be used by other applications, but the "django application" part is only a management script "runcode.py", which has no calls anywhere in the codebase.

**Comment by MCGallaspy** [comment]
Will it resolve the issue if you make it a "vanilla" module instead of a django app?

**Comment by benjaoming** [comment]
Yes, removing it from INSTALLED_APPS...

**Comment by benjaoming** [comment]
Issue as it appears on the .deb installer (because it didn't create a "_built.touch" file):

```
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/management/commands/kaserve.py", line 126, in handle
    self.setup_server_if_needed()
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/management/commands/kaserve.py", line 81, in setup_server_if_needed
    call_command("setup", interactive=False)
  File "/usr/share/kalite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/management/commands/setup.py", line 273, in handle
    call_command("syncdb", interactive=False, verbosity=options.get("verbosity"))
  File "/usr/share/kalite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 393, in handle
    return self.handle_noargs(**options)
  File "/usr/share/kalite/dist-packages/south/management/commands/syncdb.py", line 68, in handle_noargs
    migrations = migration.Migrations(app_label)
  File "/usr/share/kalite/dist-packages/south/migration/base.py", line 64, in __call__
    self.instances[app_label] = super(MigrationsMetaclass, self).__call__(app_label_to_app_module(app_label), **kwds)
  File "/usr/share/kalite/dist-packages/south/migration/utils.py", line 41, in app_label_to_app_module
    app = models.get_app(app_label)
  File "/usr/share/kalite/python-packages/django/db/models/loading.py", line 157, in get_app
    raise ImproperlyConfigured("App with label %s is missing a models.py module." % app_label)
ImproperlyConfigured: App with label testing is missing a models.py module.
```

**Comment by benjaoming** [comment]
Is fixed now :)
