### ISSUE TITLE
"'CENTRAL_SERVER_HOST' is not defined" error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3877]
I'm trying to replicate the #3831 by testing and installing the server from my repo on a different machine, and I'm getting the 'CENTRAL_SERVER_HOST' is not defined error. I thought it might be  similar to the #3197 error that we had in March, but it doesn't seem so: I tested with both `DEBUG = True` and `DEBUG = False` and  Central Server at hub.learningequality.org seems up and running.

**Branch**: today's develop

**Expected behavior**: After cloning and updating the repo on a new machine, the command `bin/kalite manage setup --username=admin --password=pass --noinput` should setup the new server instance. 

**Actual behavior**: Full error output here:
```
$ bin/kalite manage setup --username=admin --password=pass --noinput

Traceback (most recent call last):
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\kalitectl.py", line 707, in <module>
    manage(command, args=arguments['DJANGO_OPTIONS'])
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\kalitectl.py", line 367, in manage
    utility.execute()
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\core\management\_
_init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\core\management\_
_init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\core\management\_
_init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\conf\__init__.py"
, line 53, in __getattr__
    self._setup(name)
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\conf\__init__.py"
, line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\conf\__init__.py"
, line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\utils\importlib.p
y", line 35, in import_module
    __import__(name)
  File "d:\R\GrauMigGTR-mini\gh\ka-lite\kalite\settings\__init__.py", line 105,
in <module>
    CENTRAL_SERVER_URL = "%s://%s" % (SECURESYNC_PROTOCOL, CENTRAL_SERVER_HOST)
NameError: name 'CENTRAL_SERVER_HOST' is not defined
```

**Comment by benjaoming** [comment]
I can see this is easily fixed in the new settings refactor... but it's still unmerged, I think we'll get it in by tonight.

**Comment by radinamatic** [comment]
Okis, I'll test it tomorrow and report back.

**Comment by radinamatic** [comment]
@benjaoming ping me when you merge the fix for this so I can retest.

**Comment by benjaoming** [comment]
@radinamatic if you subscribe to #3809, you will be notified :)

**Comment by radinamatic** [comment]
Confirming that this issue is no more, after the #3809 was merged yesterday. @benjaoming
