### ISSUE TITLE
Sync Error [code=public_key_unregistered]

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3936]
I searched among the issues, but couldn't find this error referenced. 

**Branch**: latest develop  

**This is a fresh KA Lite install & db, but with `generaterealdata`.**

![device registration with public key not found](https://cloud.githubusercontent.com/assets/1457929/8353766/cfd2b12c-1b41-11e5-9ad6-201eb698ec9e.png)

Error details:
```
Checking purgatory for unsaved models...
Purgatory is model-free! Congrats!
Initiating SyncSession...
CLIENT: post register
Error [code=public_key_unregistered]: Device registration with public key not found; login and register first?


Traceback (most recent call last):

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\fle_utils\chronograph\models.py", line 209, in run_management_command
call_command(self.command, *args, **options)

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\core\management\__init__.py", line 161, in call_command
return klass.execute(*args, **defaults)

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\core\management\base.py", line 263, in execute
output = self.handle(*args, **options)

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\management\commands\syncmodels.py", line 53, in handle
result = client.start_session()

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\engine\api_client.py", line 50, in start_session
data) = self.validate_me_on_server()

File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\engine\api_client.py", line 122, in validate_me_on_server
raise Exception("Error [code=%s]: %s" % (resp.get("code",""), resp.get("error","")))

Exception: Error [code=public_key_unregistered]: Device registration with public key not found; login and register first?
```

**Current Behavior/Steps to reproduce**:

1. Pull the repo from GH & install KA Lite
2. Log in as Admin
3. Register the device
4. Try syncing

**Comment by radinamatic** [comment]
OTOH, I've always found the part

__Zone for public key MIIBCgKCAQEA...__ 

very cryptic. 

Are we presuming all potential KA Lite admins around the world would know what is that about (I know, I don't :(

**Comment by radinamatic** [comment]
Non extant, closing!
