### ISSUE TITLE
Error "column id is not unique" on vieweing videos

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3949]
**Branch**: latest develop  

Trying to see if I can pinpoint the delays as per #3835, I bumped into this error, but haven't been able to reproduce it. Eli reported something similar in January, but it's apparently been resolved. I'm reporting it anyway just in case it can ring some bells for somebody. 

**Current Behavior**: Choosing various videos from the sidebar menu, appears the error alert:

`column id is not unique` 

with the following traceback **(video still gets loaded and plays bellow the traceback)** 

Traceback (most recent call last): File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 195, in wrapper response = callback(request, *args, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 426, in dispatch_list return self.dispatch('list', request, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 458, in dispatch response = method(request, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 1320, in post_list updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs)) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 2084, in obj_create return self.save(bundle) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\tastypie\resources.py", line 2230, in save bundle.obj.save() File "d:\R\GrauMigGTR-mini\gh\ka-lite\kalite\main\models.py", line 78, in save super(VideoLog, self).save(*args, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\engine\models.py", line 478, in save super(DeferredCountSyncedModel, self).save(*args, increment_counters=increment_counters, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\engine\models.py", line 456, in save super(DeferredSignSyncedModel, self).save(*args, sign=sign, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\securesync\engine\models.py", line 385, in save super(SyncedModel, self).save(*args, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\models\base.py", line 546, in save force_update=force_update, update_fields=update_fields) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\models\base.py", line 650, in save_base result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\models\manager.py", line 215, in _insert return insert_query(self.model, objs, fields, **kwargs) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\models\query.py", line 1661, in insert_query return query.get_compiler(using=using).execute_sql(return_id) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\models\sql\compiler.py", line 937, in execute_sql cursor.execute(sql, params) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\backends\util.py", line 41, in execute return self.cursor.execute(sql, params) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\backends\sqlite3\base.py", line 364, in execute six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2]) File "d:\R\GrauMigGTR-mini\gh\ka-lite\python-packages\django\db\backends\sqlite3\base.py", line 362, in execute return Database.Cursor.execute(self, query, params) IntegrityError: column id is not unique 

**Steps to reproduce**: Unsure, I wasn't able to reproduce it.

**Comment by radinamatic** [comment]
In case it makes a difference, the video where the error appeared is this:
/math/early-math/cc-early-math-counting-topic/cc-early-math-comparing-numbers/comparing-numbers-through-10-example/

It plays fine now...

**Comment by rtibbles** [comment]
I believe this error would happen if a VideoLog is initialized, and not saved, and then another VideoLog is created.

Then both videologs get saved, having both been initialized with the same id, giving this error.

I have seen this error while trying to bulk save newly initialized logs during tests.

@jamalex Does this sound right in terms of what is happening in securesync underlying this?

**Comment by radinamatic** [comment]
Seems long gone, closing!
