### ISSUE TITLE
Document the download and installation instructions for assesment.zip 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3950]
I spent some time searching for this the other day and found the command inside the HipChat history, which is not available outside our "family"...

There is a mention in 0.13 Release notes, but it gives no details on how to deal with it if you didn't do it during the installation process. I just added the download & installation instruction into the [Getting started wiki](https://github.com/learningequality/ka-lite/wiki/Getting-started), and I leave it to you to decide if & where should it go in the sphinx docs dev docs...

**Comment by aronasorman** [comment]
Hmm this might warrant an entry in the FAQ. Sounds good to you @radinamatic?

**Comment by radinamatic** [comment]
Sure, @aronasorman, I could definitely add it to [FAQ](https://github.com/learningequality/ka-lite/blob/0.13.x/sphinx-docs/faq.rst), and maybe [Admin User Manual](https://github.com/learningequality/ka-lite/blob/master/sphinx-docs/usermanual/userman_admin.rst) too?

**Comment by aronasorman** [comment]
Sounds good to me (thumbsup)

**Comment by radinamatic** [comment]
Fixed in #3953.

**Comment by mascot6699** [comment]
I was following [Manually setting up KA Lite](https://github.com/learningequality/ka-lite/wiki/Getting-started#manually-setting-up-ka-lite) and in the last step the command 
```
./manage.py unpack_assessment_zip -f https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip
```
did not work. It said

```
Unknown command: 'unpack_assessment_zip'
Type 'manage.py help' for usage.
```
so I tried it. 

```
./manage.py --help 
Usage: manage.py subcommand [options] [args]

Options:
  -v VERBOSITY, --verbosity=VERBOSITY
                        Verbosity level; 0=minimal output, 1=normal output,
                        2=verbose output, 3=very verbose output
  --settings=SETTINGS   The Python path to a settings module, e.g.
                        "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be
                        used.
  --pythonpath=PYTHONPATH
                        A directory to add to the Python path, e.g.
                        "/home/djangoprojects/myproject".
  --traceback           Print traceback on exception
  --auto-pdb            Break into PDB on an uncaught exception
  --version             show program's version number and exit
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "./manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "./python-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "./python-packages/django/core/management/__init__.py", line 390, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "./python-packages/django/core/management/__init__.py", line 242, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "./python-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "./python-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "./python-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "./python-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "./python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/kuliza213/Umang/Training/Python/UmangGithub/ka-lite/kalite/project/settings/default.py", line 3, in <module>
    DEFAULT_USER_SETTINGS_FILE = os.path.join(os.environ["KALITE_HOME"], 'settings.py')
  File "/home/kuliza213/Umang/VirtualEnvironments/kalite-env/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'KALITE_HOME'
```

So do I need to export some variables (such as KALITE_HOME) which are not mentioned in the steps of wiki ?

**Comment by mascot6699** [comment]
Also in the alternative step to that command where exactly do I need to unzip the contents of .zip file that I downloaded.

**Comment by radinamatic** [comment]
@mascot6699 yes, I'm getting the same error. 

Could you file a separate issue? Be sure to follow the [Guidelines for contributing](https://github.com/learningequality/ka-lite/blob/master/CONTRIBUTING.md).

**Comment by mascot6699** [comment]
I have just added the issue #4164
