### ISSUE TITLE
`kalite start` should handle issues with acquiring port more gracefully

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4004]
Running: http://ppa.launchpad.net/benjaoming/ka-lite/ubuntu/pool/main/k/ka-lite-source/ka-lite_0.14.alpha2-0ubuntu1_all.deb on Ubuntu (but assuming this is more general)

I had KA Lite running elsewhere, then installed, and went to the command line to try the `kalite start` command:

    jamalex@ace:~$ kalite start
    Running 'kalite start' as daemon (system service)

    Stand by while the server loads its data...

    INFO:kalite:Invalidating the web cache.
    INFO:kalite:Running videoscan.
    INFO:kalite:Preloading exercise data for language en.
    INFO:kalite:Preloading content data for language en.
    INFO:kalite:Preloading topic tree data for language en.
    INFO:kalite:Preloading exercise data for language es.
    INFO:kalite:Preloading content data for language es.
    INFO:kalite:Preloading topic tree data for language es.
    INFO:kalite:Copying static media...
    WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
      warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

    To access KA Lite from another connected computer, try the following address(es):
        http://192.168.2.123:8008/
        http://10.8.0.1:8008/
    To access KA Lite from this machine, try the following address:
        http://127.0.0.1:8008/
    Going to daemon mode, logging to /home/jamalex/.kalite/server.log
    Exception in thread cronserver_blocking (most likely raised during interpreter shutdown):

Looking at the log file shows it didn't gracefully handle the fact that the desired port was taken, to inform the user of that fact:

    jamalex@ace:~$ cat /home/jamalex/.kalite/server.log
    [02/Jul/2015:17:27:33] ENGINE Listening for SIGHUP.
    INFO:cherrypy.error:[02/Jul/2015:17:27:33] ENGINE Listening for SIGHUP.
    [02/Jul/2015:17:27:33] ENGINE Listening for SIGTERM.
    INFO:cherrypy.error:[02/Jul/2015:17:27:33] ENGINE Listening for SIGTERM.
    [02/Jul/2015:17:27:33] ENGINE Listening for SIGUSR1.
    INFO:cherrypy.error:[02/Jul/2015:17:27:33] ENGINE Listening for SIGUSR1.
    [02/Jul/2015:17:27:33] ENGINE Bus STARTING
    INFO:cherrypy.error:[02/Jul/2015:17:27:33] ENGINE Bus STARTING
    [02/Jul/2015:17:27:33]  Loading and serving the Django application
    INFO:cherrypy.error:[02/Jul/2015:17:27:33]  Loading and serving the Django application
    [02/Jul/2015:17:27:33] ENGINE Started monitor thread '_TimeoutMonitor'.
    INFO:cherrypy.error:[02/Jul/2015:17:27:33] ENGINE Started monitor thread '_TimeoutMonitor'.
    [02/Jul/2015:17:27:38] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f7c9faa1cd0>>
    Traceback (most recent call last):
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 197, in publish
        output.append(listener(*args, **kwargs))
      File "/usr/share/kalite/python-packages/cherrypy/_cpserver.py", line 151, in start
        ServerAdapter.start(self)
      File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 167, in start
        wait_for_free_port(*self.bind_addr)
      File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 410, in wait_for_free_port
        raise IOError("Port %r not free on %r" % (port, host))
    IOError: Port 8008 not free on '0.0.0.0'

    ERROR:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f7c9faa1cd0>>
    Traceback (most recent call last):
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 197, in publish
        output.append(listener(*args, **kwargs))
      File "/usr/share/kalite/python-packages/cherrypy/_cpserver.py", line 151, in start
        ServerAdapter.start(self)
      File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 167, in start
        wait_for_free_port(*self.bind_addr)
      File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 410, in wait_for_free_port
        raise IOError("Port %r not free on %r" % (port, host))
    IOError: Port 8008 not free on '0.0.0.0'

    [02/Jul/2015:17:27:38] ENGINE Shutting down due to error in start listener:
    Traceback (most recent call last):
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 235, in start
        self.publish('start')
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 215, in publish
        raise exc
    ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

    ERROR:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Shutting down due to error in start listener:
    Traceback (most recent call last):
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 235, in start
        self.publish('start')
      File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 215, in publish
        raise exc
    ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

    [02/Jul/2015:17:27:38] ENGINE Bus STOPPING
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Bus STOPPING
    [02/Jul/2015:17:27:38] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
    [02/Jul/2015:17:27:38] ENGINE Stopped thread '_TimeoutMonitor'.
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Stopped thread '_TimeoutMonitor'.
    [02/Jul/2015:17:27:38] ENGINE Bus STOPPED
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Bus STOPPED
    [02/Jul/2015:17:27:38] ENGINE Bus EXITING
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Bus EXITING
    [02/Jul/2015:17:27:38] ENGINE Bus EXITED
    INFO:cherrypy.error:[02/Jul/2015:17:27:38] ENGINE Bus EXITED

**Comment by benjaoming** [comment]
Covered in #4014
