### ISSUE TITLE
'TypeError: 'NoneType' object is not callable' after running 'kalite manage generaterealdata'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4012]
**Branch**: 0.14 with alpha2 installer on Ubuntu 

**Actual behavior**: `kalite manage generaterealdata` finished without issues, but after starting the server ('kalite start'), appears the `TypeError: 'NoneType' object is not callable` error (**in red**) in the Terminal. Viewing in browser gives the:  

![883346fa-20ec-11e5-98da-b0a9f68fe862 1](https://cloud.githubusercontent.com/assets/1457929/8502945/848d70ae-21b7-11e5-9f10-164a81f45203.png)

`kalite start --traceback` gives this output:

```
...
To access KA Lite from another connected computer, try the following address(es):
  http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
  http://127.0.0.1:8008/
Going to daemon mode, logging to /home/didi/.kalite/server.log
Unhandled exception in thread started by <bound method ManageThread.__bootstrap of <ManageThread(cronserver_blocking, stopped -1345234112)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 823, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
didi@didihp:~$
```

**Expected behavior**: Clean server restart with working database after generating real data.  

**Steps to reproduce**:

1. Install & configure alpha2 deb on Ubuntu (I had 2 language packs, 10 videos, 2 learners...)
2. Stop kalite and run `kalite manage generaterealdata`. 
3. Restart kalite.

**Comment by radinamatic** [comment]
Retried to start the server today, and no bloody error message appeared in Terminal, but I'm still getting the 'Database locked' error in browser. @jamalex mentioned in #4006 that in his case everything runs smoothly with `--foreground`, so I tried that too:

```
didi@didihp:~$ kalite start --foreground
Running 'kalite start' in foreground...

Stand by while the server loads its data...

INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Preloading exercise data for language es.
INFO:kalite:Preloading content data for language es.
INFO:kalite:Preloading topic tree data for language es.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
[04/Jul/2015:22:05:47] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[04/Jul/2015:22:05:47] ENGINE Listening for SIGHUP.
[04/Jul/2015:22:05:47] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[04/Jul/2015:22:05:47] ENGINE Listening for SIGTERM.
[04/Jul/2015:22:05:47] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[04/Jul/2015:22:05:47] ENGINE Listening for SIGUSR1.
[04/Jul/2015:22:05:47] ENGINE Bus STARTING
INFO:cherrypy.error:[04/Jul/2015:22:05:47] ENGINE Bus STARTING
[04/Jul/2015:22:05:47]  Loading and serving the Django application
INFO:cherrypy.error:[04/Jul/2015:22:05:47]  Loading and serving the Django application
[04/Jul/2015:22:05:47] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:cherrypy.error:[04/Jul/2015:22:05:47] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:kalite:Running 1 due jobs... ("Secure Sync")
WARNING:py.warnings:/usr/share/kalite/python-packages/fle_utils/set_process_priority.py:78: DeprecationWarning: set_ionice() is deprecated; use ionice() instead
  this_process.set_ionice(psutil.IOPRIO_CLASS_IDLE)

[04/Jul/2015:22:05:52] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0xb6cff04c>>
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/kalite/python-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 167, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 410, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8008 not free on '0.0.0.0'

ERROR:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0xb6cff04c>>
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 197, in publish
    output.append(listener(*args, **kwargs))
  File "/usr/share/kalite/python-packages/cherrypy/_cpserver.py", line 151, in start
    ServerAdapter.start(self)
  File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 167, in start
    wait_for_free_port(*self.bind_addr)
  File "/usr/share/kalite/python-packages/cherrypy/process/servers.py", line 410, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8008 not free on '0.0.0.0'

[04/Jul/2015:22:05:52] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

ERROR:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 235, in start
    self.publish('start')
  File "/usr/share/kalite/python-packages/cherrypy/process/wspbus.py", line 215, in publish
    raise exc
ChannelFailures: IOError("Port 8008 not free on '0.0.0.0'",)

[04/Jul/2015:22:05:52] ENGINE Bus STOPPING
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Bus STOPPING
[04/Jul/2015:22:05:52] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) already shut down
[04/Jul/2015:22:05:52] ENGINE Stopped thread '_TimeoutMonitor'.
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Stopped thread '_TimeoutMonitor'.
[04/Jul/2015:22:05:52] ENGINE Bus STOPPED
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Bus STOPPED
[04/Jul/2015:22:05:52] ENGINE Bus EXITING
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Bus EXITING
[04/Jul/2015:22:05:52] ENGINE Bus EXITED
INFO:cherrypy.error:[04/Jul/2015:22:05:52] ENGINE Bus EXITED
didi@didihp:~$ 

```

**Comment by benjaoming** [comment]
@radinamatic 
The fact that the port is occupied and the database is locked suggests that you have another kalite running.

You can identify the process like this:

    ps ax | grep kalite

Then note the process ID of the process that's running the server ("something ... kalite start"). You can kill it with "kill 12345" and if that doesn't work you can really kill it with "kill -9 12345".

**Comment by radinamatic** [comment]
I tried stopping and killing the process to no avail, even thought it apparently worked for @66eli77 this morning: 

```
didi@didihp:~$ kalite start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Preloading exercise data for language es.
INFO:kalite:Preloading content data for language es.
INFO:kalite:Preloading topic tree data for language es.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
Going to daemon mode, logging to /home/didi/.kalite/server.log
TypeError: 'NoneType' object is not callable
Unhandled exception in thread started by <bound method ManageThread.__bootstrap of <ManageThread(cronserver_blocking, started -1345270976)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 857, in __bootstrap_inner
didi@didihp:~$ ps ax | grep kalite
 3708 ?        Sl     0:00 /usr/bin/python2 /usr/share/kalite/kalitectl.py start
 3745 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kalite stop
Already stopped. Status was: Not responding
Not responding, killing with force
kalite stopped
didi@didihp:~$ ps ax | grep kalite
 3764 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kill 3764
bash: kill: (3764) - No such process
didi@didihp:~$ kill -9 3764
bash: kill: (3764) - No such process
didi@didihp:~$ ps ax | grep kalite
 3766 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kalite start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Preloading exercise data for language es.
INFO:kalite:Preloading content data for language es.
INFO:kalite:Preloading topic tree data for language es.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
Going to daemon mode, logging to /home/didi/.kalite/server.log
TypeError: 'NoneType' object is not callable
Exception in thread cronserver_blocking (most likely raised during interpreter shutdown):didi@didihp:~$ 
``` 
```
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
Going to daemon mode, logging to /home/didi/.kalite/server.log
TypeError: 'NoneType' object is not callable
Exception in thread cronserver_blocking (most likely raised during interpreter shutdown):didi@didihp:~$ kalips ax | grep kalite
 3780 ?        Sl     0:00 /usr/bin/python2 /usr/share/kalite/kalitectl.py start
 3813 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kill 3780
didi@didihp:~$ kalite start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Preloading exercise data for language es.
INFO:kalite:Preloading content data for language es.
INFO:kalite:Preloading topic tree data for language es.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
Going to daemon mode, logging to /home/didi/.kalite/server.log
TypeError: 'NoneType' object is not callable
didi@didihp:~$ 
```

**Comment by radinamatic** [comment]
Last try with `--foreground`, at this point I'm waiting for alpha3:

```
Going to daemon mode, logging to /home/didi/.kalite/server.log
TypeError: 'NoneType' object is not callable
didi@didihp:~$ ps ax | grep kalite
 3867 ?        Sl     0:00 /usr/bin/python2 /usr/share/kalite/kalitectl.py start
 3891 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kill -9 3867
didi@didihp:~$ ps ax | grep kalite
 3894 pts/4    S+     0:00 grep --color=auto kalite
didi@didihp:~$ kalite start --foreground
Running 'kalite start' in foreground...

Stand by while the server loads its data...

INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Preloading exercise data for language es.
INFO:kalite:Preloading content data for language es.
INFO:kalite:Preloading topic tree data for language es.
INFO:kalite:Copying static media...
WARNING:py.warnings:/usr/share/kalite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

To access KA Lite from another connected computer, try the following address(es):
	http://192.168.1.39:8008/
To access KA Lite from this machine, try the following address:
	http://127.0.0.1:8008/
[06/Jul/2015:18:10:12] ENGINE Listening for SIGHUP.
INFO:cherrypy.error:[06/Jul/2015:18:10:12] ENGINE Listening for SIGHUP.
[06/Jul/2015:18:10:12] ENGINE Listening for SIGTERM.
INFO:cherrypy.error:[06/Jul/2015:18:10:12] ENGINE Listening for SIGTERM.
[06/Jul/2015:18:10:12] ENGINE Listening for SIGUSR1.
INFO:cherrypy.error:[06/Jul/2015:18:10:12] ENGINE Listening for SIGUSR1.
[06/Jul/2015:18:10:12] ENGINE Bus STARTING
INFO:cherrypy.error:[06/Jul/2015:18:10:12] ENGINE Bus STARTING
[06/Jul/2015:18:10:12]  Loading and serving the Django application
INFO:cherrypy.error:[06/Jul/2015:18:10:12]  Loading and serving the Django application
[06/Jul/2015:18:10:12] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:cherrypy.error:[06/Jul/2015:18:10:12] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:kalite:Running 1 due jobs... ("Secure Sync")
[06/Jul/2015:18:10:13] ENGINE Serving on 0.0.0.0:8008
INFO:cherrypy.error:[06/Jul/2015:18:10:13] ENGINE Serving on 0.0.0.0:8008
[06/Jul/2015:18:10:13] ENGINE Bus STARTED
INFO:cherrypy.error:[06/Jul/2015:18:10:13] ENGINE Bus STARTED
WARNING:py.warnings:/usr/share/kalite/python-packages/fle_utils/set_process_priority.py:78: DeprecationWarning: set_ionice() is deprecated; use ionice() instead
  this_process.set_ionice(psutil.IOPRIO_CLASS_IDLE)
```

**Comment by benjaoming** [comment]
@radinamatic the last attempt doesn't seem to have errors?

**Comment by radinamatic** [comment]
I could have swore there was a red message somewhere in there, but the box is booted in W7 right now, so I can't check... Do you need a feedback on this, or should I just wait for alpha3? @benjaoming

**Comment by benjaoming** [comment]
alpha3 is out already ;)

**Comment by radinamatic** [comment]
Great, will test it first thing tomorrow morning... Thanks! :)

**Comment by benjaoming** [comment]
no please test alpha4 then ;)

**Comment by radinamatic** [comment]
Gee, when did that happen...? :yum: 
Using the `apt-get install ka-lite`, right? Because the packages on Launchpad still say `0.14.alpha2`.

**Comment by benjaoming** [comment]
You may have to "apt-get update" first?

**Comment by radinamatic** [comment]
Good work, @benjaoming, this error is no more too... :+1:
