### ISSUE TITLE
"Syncmodels" no longer works

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4032]
(ka-lite)jamalex@hummingbird:~/fle/ka-lite$ bin/kalite manage syncmodels
    Checking purgatory for unsaved models...
    Purgatory is model-free! Congrats!
    Initiating SyncSession...
    Syncing models...
    Traceback (most recent call last):
      File "/home/jamalex/fle/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/jamalex/fle/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
        output = self.handle(*args, **options)
      File "/home/jamalex/fle/ka-lite/python-packages/securesync/management/commands/syncmodels.py", line 62, in handle
        results = client.sync_models()
      File "/home/jamalex/fle/ka-lite/python-packages/securesync/engine/api_client.py", line 251, in sync_models
        counters_to_download, counters_to_upload = self.sync_device_records()
      File "/home/jamalex/fle/ka-lite/python-packages/securesync/engine/api_client.py", line 162, in sync_device_records
        client_counters = self.get_client_device_counters()
      File "/home/jamalex/fle/ka-lite/python-packages/securesync/engine/api_client.py", line 154, in get_client_device_counters
        return get_device_counters(zone=self.session.client_device.get_zone())
      File "/home/jamalex/fle/ka-lite/python-packages/securesync/engine/utils.py", line 71, in get_device_counters
        device_counters[device.id] += cnt()
    TypeError: 'int' object is not callable

This problem was introduced by @benjaoming's refactoring on May 24, in https://github.com/learningequality/ka-lite/commit/57eb94b2. Looks like code was moved and modified quite a bit at the same time, but I'll do my best to go back and review that commit, to make sure I don't see anything else.

We're not catching this in our tests because sync test coverage lives in the ecosystem tests in ka-lite-central, but ka-lite is no longer compatible with ka-lite-central, due to the settings refactor.

**Comment by benjaoming** [comment]
Sorry, looks like the paranthesis are a left-over brain fart from here:

https://github.com/learningequality/ka-lite/blob/master/python-packages/securesync/engine/__init__.py#L83

The refactor was getting rid of __init__ files causing circular module load order.

**Comment by benjaoming** [comment]
This was actually reported by @66eli77 in #3852

@66eli77 when reporting, please remember to put labels, milestones etc :)

**Comment by benjaoming** [comment]
This *could* be the only issue, just making the PR and trying it out in alpha4 in some time.

**Comment by jamalex** [comment]
According to some testing, looks like it was just the parentheses! Working now.
