### ISSUE TITLE
Fix imports relying on wrong path

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4132]
Here's an example of an import that assumes that we added the *contents* of the `kalite` package to the python path:

```
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/django/core/management/commands/test.py", line 80, in execute
    super(Command, self).execute(*args, **options)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/share/kalite/dist-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/usr/share/kalite/python-packages/django/core/management/commands/test.py", line 106, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/lib/python2.7/dist-packages/kalite/testing/testrunner.py", line 117, in run_tests
    return run_tests_wrapper_fn()
  File "/usr/lib/python2.7/dist-packages/kalite/testing/testrunner.py", line 116, in run_tests_wrapper_fn
    return super(KALiteTestRunner, self).run_tests(test_labels, extra_tests, **kwargs)
  File "/usr/share/kalite/python-packages/django/test/simple.py", line 366, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/usr/lib/python2.7/dist-packages/kalite/testing/testrunner.py", line 167, in build_suite
    suite = super(KALiteTestRunner, self).build_suite(test_labels, extra_tests, **kwargs)
  File "/usr/share/kalite/python-packages/django/test/simple.py", line 260, in build_suite
    suite.addTest(build_suite(app))
  File "/usr/share/kalite/python-packages/django/test/simple.py", line 68, in build_suite
    test_module = get_tests(app_module)
  File "/usr/share/kalite/python-packages/django/test/simple.py", line 25, in get_tests
    test_module = import_module('.'.join(prefix + [TEST_MODULE]))
  File "/usr/share/kalite/python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/tests/__init__.py", line 5, in <module>
    from browser_tests import *
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/tests/browser_tests/__init__.py", line 2, in <module>
    from coachreports import *
ImportError: No module named coachreports
```

All these `xyz` imports should be changed to ``kalite.xyz`.

**Comment by benjaoming** [comment]
Problem is small luckily :)

```
ack-grep --python '^\s*(import|from)\s+(testing|legacy|student_testing|settings|topic_tools|contentload|coachreports|project|shared|django_cherrypy_wsgiserver|main|store|caching|dynamic_assets|ab_testing|i18n|inline|database|playlist|distributed|updates|basetests|static|remoteadmin|control_panel|facility)' kalite
kalite/distributed/tests/browser_tests/__init__.py
2:from coachreports import *
3:from control_panel import *
4:from distributed import *
9:from student_testing import *

kalite/control_panel/tests/__init__.py
1:from control_panel import *
```

**Comment by MCGallaspy** [comment]
Can you describe how to reproduce the ImportError?

**Comment by benjaoming** [comment]
`kalite test` did it from the PPA source.

**Comment by benjaoming** [comment]
But actually this might be happening because of something else? Was my guess wrong maybe and its unrelated to the path being wrongly set? I remember we used to have ka-lite/kalite in the path.
