### ISSUE TITLE
DEBUG:kalite:No jobs due to run.

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4158]
**Branch**: develop on Ubuntu 15.04

**Current Behavior**: I've been noticing this for a few days now, `DEBUG:kalite:No jobs due to run.` pops up in the Terminal even when `kalite` is expressly stopped:

```
// kalite running
127.0.0.1 - - [24/Jul/2015:21:50:02] "GET /static/js/distributed/perseus/ke/third_party/MathJax/2.1/extensions/MathZoom.js HTTP/1.1" 404 1482 "http://127.0.0.1:8008/learn/khan/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.130 Chrome/43.0.2357.130 Safari/537.36"
INFO:cherrypy.access.140699635359184:127.0.0.1 - - [24/Jul/2015:21:50:02] "GET /static/js/distributed/perseus/ke/third_party/MathJax/2.1/extensions/MathZoom.js HTTP/1.1" 404 1482 "http://127.0.0.1:8008/learn/khan/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.130 Chrome/43.0.2357.130 Safari/537.36"
DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
^C                                                        // me stopping the server
Traceback (most recent call last):
  File "bin/kalite", line 112, in <module>
    p.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 796, in communicate
    self.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
[24/Jul/2015:22:20:58] ENGINE Keyboard Interrupt: shutting down bus
INFO:cherrypy.error:[24/Jul/2015:22:20:58] ENGINE Keyboard Interrupt: shutting down bus
[24/Jul/2015:22:20:58] ENGINE Bus STOPPING
INFO:cherrypy.error:[24/Jul/2015:22:20:58] ENGINE Bus STOPPING
didi@didi-Inspiron-3531:~/ka-lite$ [24/Jul/2015:22:20:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) shut down
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8008)) shut down
[24/Jul/2015:22:20:59] ENGINE Stopped thread '_TimeoutMonitor'.
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Stopped thread '_TimeoutMonitor'.
[24/Jul/2015:22:20:59] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Stopped thread 'Autoreloader'.
[24/Jul/2015:22:20:59] ENGINE Bus STOPPED
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Bus STOPPED
[24/Jul/2015:22:20:59] ENGINE Bus EXITING
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Bus EXITING
[24/Jul/2015:22:20:59] ENGINE Bus EXITED
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Bus EXITED
[24/Jul/2015:22:20:59] ENGINE Waiting for child threads to terminate...
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Waiting for child threads to terminate...
[24/Jul/2015:22:20:59] ENGINE Waiting for thread cronserver_blocking --traceback.
INFO:cherrypy.error:[24/Jul/2015:22:20:59] ENGINE Waiting for thread cronserver_blocking --traceback.
didi@didi-Inspiron-3531:~/ka-lite$ bin/kalite stop          // me stopping again
Already stopped. Status was: Stopped
kalite stopped
didi@didi-Inspiron-3531:~/ka-lite$                     //after a while 
DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
^C
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.
```

I wouldn't mind if it didn't jump at me in the middle of rebase in Vim, which can still be a delicate operation sometimes...

**Comment by benjaoming** [comment]
The develop isn't updated with latest fixes from 0.14.x

Please try again when #4165 is merged!

**Comment by radinamatic** [comment]
Subscribed and waiting for the merge!
(mighty annoying this one)

**Comment by benjaoming** [comment]
To kill all the loose processes:

    pkill -9 kalite

To run kalite without the wild-going cronserver

    kalite start --skip-job-scheduler

**Comment by radinamatic** [comment]
That's what I get for not RTD-ing! :P 
Thanks!

**Comment by radinamatic** [comment]
Apparently, **kalite is too tough to kill**... :D 

```
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
^C
didi@didi-Inspiron-3531:~/ka-lite$ pkill -9 kalite
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.
```

**Comment by benjaoming** [comment]
`ps ax|grep kalite` will show you the exact processes and you can kill them by number with `kill 1234`.

**Comment by radinamatic** [comment]
Too tough to kill, indeed...

```
didi@didi-Inspiron-3531:~/ka-lite$ ps ax|grep kalite
 1762 pts/0    Sl     2:35 /usr/bin/python2 /home/didi/ka-lite/kalitectl.py start --foreground --watch --settings=kalite.project.settings.dev
 3033 pts/0    S+     0:00 grep --color=auto kalite
didi@didi-Inspiron-3531:~/ka-lite$ kill 1762
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.
```

**Comment by benjaoming** [comment]
Try `kill -9 1762`

**Comment by radinamatic** [comment]
`kill -9` is **the** killer!

**Comment by benjaoming** [comment]
Yes but be careful!

![like this dog](http://i3.cpcache.com/product/96860797/kill_9_dog_tshirt.jpg?color=White&height=460&width=460&qv=90)

**Comment by radinamatic** [comment]
That's too cute a face for a  `k(ill)-9` killer!

**Comment by radinamatic** [comment]
#4165 is now merged, but `DEBUG:kalite:No jobs due to run.` is still there. :(

**Comment by benjaoming** [comment]
@radinamatic - just to be sure... "still there" after closing KA Lite? Because the message is not an error in itself, only if it shows up after stopping KA Lite.

**Comment by radinamatic** [comment]
```
...
Watchify: Starting watcher
Watchify: 1197798 bytes written (56.08 seconds)
Watchify: 13 Bundles written.
DEBUG:kalite:No jobs due to run.
DEBUG:kalite:No jobs due to run.
^C              ///// I'm stopping here with CTRL+C
didi@didi-Inspiron-3531:~/ka-lite$ bin/kalite stop   //// I'm stopping here with kalite stop
kalite stopped
didi@didi-Inspiron-3531:~/ka-lite$ ps ax|grep kalite
13513 pts/0    Sl     5:41 /usr/bin/python2 /home/didi/ka-lite/kalitectl.py start --foreground --watch --settings=kalite.project.settings.dev
```
The process `13513` is the culprit, but it's not the command with which I started the server this time, it's like second before it! Could it be the the `--foreground` flag?

```  
15946 pts/0    S+     0:00 grep --color=auto kalite
didi@didi-Inspiron-3531:~/ka-lite$ DEBUG:kalite:No jobs due to run.    //// Here it is again!
^C
didi@didi-Inspiron-3531:~/ka-lite$ kill -9 13513         //// The only way to kill it :)
didi@didi-Inspiron-3531:~/ka-lite$ ps ax|grep kalite
16224 pts/0    S+     0:00 grep --color=auto kalite
didi@didi-Inspiron-3531:~/ka-lite$ bin/kalite start --skip-job-scheduler --watch --settings=kalite.project.settings.dev
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...
...
and so on...
```

Now I'm starting it with `--skip-job-scheduler ` as per your recommendation! :)

**Comment by radinamatic** [comment]
Non extant, closing!
