### ISSUE TITLE
Unable to use manage.py commands when following contributing guidelines for manually setting up KA Lite

### ISSUE THREAD

**Issue by mascot6699** [learningequality/ka-lite#4164]
The branch I am talking about is develop

**Expected behavior**
The command 
```
./manage.py unpack_assessment_zip -f https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip
```
should download and unpack the zip file at correct place. Also there was no options for ignore/accept the download of assessment files in installation process as the wiki hinted

**Actual Behaviour**
The file manage.py is not able to recognized the command

**Steps to reproduce**
I was following [Manually setting up KA Lite](https://github.com/learningequality/ka-lite/wiki/Getting-started#manually-setting-up-ka-lite) and in the last step the command 
```
./manage.py unpack_assessment_zip -f https://learningequality.org/downloads/ka-lite/0.14/content/assessment.zip
```
did not work. It said

```
Unknown command: 'unpack_assessment_zip'
Type 'manage.py help' for usage.
```
so I tried it. 

```
./manage.py --help 
Usage: manage.py subcommand [options] [args]

Options:
  -v VERBOSITY, --verbosity=VERBOSITY
                        Verbosity level; 0=minimal output, 1=normal output,
                        2=verbose output, 3=very verbose output
  --settings=SETTINGS   The Python path to a settings module, e.g.
                        "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be
                        used.
  --pythonpath=PYTHONPATH
                        A directory to add to the Python path, e.g.
                        "/home/djangoprojects/myproject".
  --traceback           Print traceback on exception
  --auto-pdb            Break into PDB on an uncaught exception
  --version             show program's version number and exit
  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "./manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "./python-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "./python-packages/django/core/management/__init__.py", line 390, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "./python-packages/django/core/management/__init__.py", line 242, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "./python-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "./python-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "./python-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "./python-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "./python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/kuliza213/Umang/Training/Python/UmangGithub/ka-lite/kalite/project/settings/default.py", line 3, in <module>
    DEFAULT_USER_SETTINGS_FILE = os.path.join(os.environ["KALITE_HOME"], 'settings.py')
  File "/home/kuliza213/Umang/VirtualEnvironments/kalite-env/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'KALITE_HOME'
```

**Question**
So do I need to export some variables (such as KALITE_HOME) which are not mentioned in the steps of wiki ?

**Comment by aronasorman** [comment]
Hi @mascot6699,

Thanks for filing this issue. For the develop branch the `manage.py` command has been obsolete and thus unmaintained, which is why you get the message. If you're planning to use your current KA Lite repo for use in production you  can run:


```bash
pip install -e .
```

That should link your KA Lite repo to your system packages. From there you can run:

```bash
kalite manage unpack_assessment_zip <zip>
```

to extract the assessment items.

**Comment by radinamatic** [comment]
This implies that we'll have to amend the **Get started wiki** and the admin manual, so what command should actually be used to install assessment items in development repo? @aronasorman

**Comment by mascot6699** [comment]
Was able to do that. Thanks!

**Comment by aronasorman** [comment]
@radinamatic we'll probably migrate everyone to the official docs' contributing page. I'll change the Getting Started wiki to point to that.
