### ISSUE TITLE
Occasional test timeout

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4314]
On `develop`, I got the following test failure once:

```python
 Scenario: I finished viewing the details of the exercise  # kalite/coachreports/features/coachreports.feature:48
    Given I am on the detail panel                          # kalite/coachreports/features/steps/coachreports.py:58
    Given I am on the detail panel                          # kalite/coachreports/features/steps/coachreports.py:58 2.419s
    When I click on the partial colored cell                # kalite/coachreports/features/steps/coachreports.py:248
    When I click on the partial colored cell                # kalite/coachreports/features/steps/coachreports.py:248 25.796s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/coachreports/features/steps/coachreports.py", line 250, in impl
          click_and_wait_for_id_to_appear(context, find_css_with_wait(context, "td.partial"), "details-panel-view")
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 130, in click_and_wait_for_id_to_appear
          return id_shown_with_wait(context, elem_wait, wait_time=wait_time)
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 217, in id_shown_with_wait
          return _shown_elem_with_wait(context, (By.ID, id_str), **kwargs)
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 283, in _shown_elem_with_wait
          lambda browser: _visibility()
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 66, in until
          value = method(self._driver)
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 283, in <lambda>
          lambda browser: _visibility()
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 276, in _visibility
          elem = context.browser.find_element(by[0], by[1])
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 664, in find_element
          {'using': by, 'value': value})['value']
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
          response = self.command_executor.execute(driver_command, params)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 349, in execute
          return self._request(command_info[0], url, body=data)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 380, in _request
          resp = self._conn.getresponse()
        File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/httplib.py", line 1073, in getresponse
          response.begin()
        File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/httplib.py", line 415, in begin
          version, status, reason = self._read_status()
        File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/httplib.py", line 371, in _read_status
          line = self.fp.readline(_MAXLINE + 1)
        File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/socket.py", line 476, in readline
          data = self._sock.recv(self._rbufsize)
      timeout: timed out
```

Going to increase the wait time on that function, in order to avoid similar future errors _or_ if it appears the test is prone to race condition I'll fix it up.

**Comment by MCGallaspy** [comment]
Hopefully using the Remote WebDriver will free up resources on the testing machines, avoiding these kinds of failures.
