### ISSUE TITLE
Running manage create_dummy_language_pack raises an exception

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#4423]
Expected behaviour: Should create a dummy language pack.

Current behaviour:
```
Traceback (most recent call last):
  File "/home/richard/github/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/richard/github/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/richard/github/ka-lite/python-packages/django/core/management/base.py", line 393, in handle
    return self.handle_noargs(**options)
  File "/home/richard/github/ka-lite/kalite/i18n/management/commands/create_dummy_language_pack.py", line 42, in handle_noargs
    langpack_zip = download_language_pack(BASE_LANGUAGE_PACK)
  File "/home/richard/github/ka-lite/kalite/i18n/management/commands/create_dummy_language_pack.py", line 64, in download_language_pack
    return zipfile.ZipFile(StringIO(resp.content))
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

**Comment by aronasorman** [comment]
Looks like we weren't building 0.15 language packs on the staging server.

**Comment by rtibbles** [comment]
Different error now:
```
KeyError: "There is no item named 'LC_MESSAGES/django.mo' in the archive"
```

**Comment by rtibbles** [comment]
Seems like the base language pack that the command is downloading has no mo files in it.

**Comment by aronasorman** [comment]
Yeah, was dbugging this last thursday. Will look further into this on Monday.

**Comment by aronasorman** [comment]
Should be fixed in https://github.com/fle-internal/ka-lite-central/commit/e4094fa1b29edabfccc594a4cc683072c80e5434.

**Comment by aronasorman** [comment]
Just need a new run of the language packs. Should be fixed tomorrow.
