### ISSUE TITLE
Cannot download videos on Mac, "DatabaseError: no such table: chronograph_job"

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4447]
Branch: 0.15.x
OS: Mac Yosemite 10.10.3
Browser: Chrome
NOTES: Mike confirm he has no problem with windows, so I think it may be mac only
Steps to replicate: 
1. run 'kalite manage setup --settings=kalite.project.settings.dev' to delete the data.sqlit file
2. start server in dev mode
3. login as admin and go to video downloading page
4. download a video and you should see the error like this
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/Eli/Desktop/ka-lite/python-packages/fle_utils/django_utils/command.py", line 61, in run
    call_command(self.cmd, *self.args, **self.kwargs)
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/Eli/Desktop/ka-lite/python-packages/fle_utils/chronograph/management/commands/cron.py", line 10, in handle
    for job in Job.objects.due():
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/models/query.py", line 123, in _result_iter
    self._fill_cache()
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/models/query.py", line 927, in _fill_cache
    self._result_cache.append(next(self._iter))
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/models/query.py", line 301, in iterator
    for row in compiler.results_iter():
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/Eli/Desktop/ka-lite/ENV/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 159, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/Eli/Desktop/ka-lite/ENV/lib/python2.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 101, in _record
    return method(sql, params)
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: chronograph_job
```

**Comment by 66eli77** [comment]
@EdDixon @aronasorman @cpauya   if you use Mac, can you verify this issue on you machine?

**Comment by cpauya** [comment]
Hi @66eli77 - I assume this is using git to setup ka-lite on your Mac and not the .dmg installer?

**Comment by 66eli77** [comment]
@cpauya you are right, not the installer

**Comment by cpauya** [comment]
Tried this with `bin/kalite manage setup --settings=kalite.project.settings.dev` but got this issue (it's a different one with @66eli77 but I think @djallado have the same issue as mine):

```bash
cyril-lappy6:ka-lite-src cyril$ bin/kalite manage setup --settings=kalite.project.settings.dev
Traceback (most recent call last):
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalitectl.py", line 945, in <module>
    manage(command, args=arguments['DJANGO_OPTIONS'])
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalitectl.py", line 407, in manage
    utility.execute()
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/python-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/python-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/python-packages/django/core/management/__init__.py", line 77, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/distributed/management/commands/setup.py", line 31, in <module>
    from kalite.topic_tools.settings import CHANNEL
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/kalite/topic_tools/__init__.py", line 35, in <module>
    from fle_utils.general import softload_json, softload_sqlite_cache, json_ascii_decoder
  File "/Users/cyril/w/fle/ka-lite/ka-lite-src/python-packages/fle_utils/general.py", line 12, in <module>
    from sqlitedict import SqliteDict
ImportError: No module named sqlitedict
```

Even running `bin/kalite manage setup` yields the same issue.

I have no `KALITE_PYTHON` or any other environment variables, I did not activate `virtualenv`, and I'm on `0.15.x` branch.

Will test some more.

**Comment by 66eli77** [comment]
@cpauya sqlitedict is a python source code module located in <your_python_source>/site-packages.
 sqlitedict should be included in your requirements.txt file. 
Try run "pip install -r requirements_dev.txt"

**Comment by 66eli77** [comment]
I tested video downloading with 0.14.x on my Mac, and it works fine. Seems like some new stuff introduced to 0.15.x cause the problem

**Comment by cpauya** [comment]
Thanks @66eli77 - yes I forgot about the `requirements_dev.txt`.  I created another virtualenv for the 0.15.x branch and was able to complete the `manage.py setup` step... resuming test on the video download today.

**Comment by cpauya** [comment]
Hi @66eli77 - here are the steps to successfully download videos

1. Select 0.15.x of ka-lite repo.
2. Activate a new virtualenv.
3. Run 'pip install -r requirements_dev.txt'
4. Run 'bin/kalite manage setup --settings=kalite.project.settings.dev'
5. When asked to run 'kalite start' - select No.  (I said Yes before and the site did not host static files like https://github.com/learningequality/installers/issues/169 - so select No here).
6. Run 'kalite manage runserver --settings=kalite.project.settings.dev'.
7. Go to http://127.0.0.1:8000/ - login, do a one-click registration, go to videos page.
8. Download a video and wait until it says "Downloaded 1 of 1 videos successfully." (It didn't show a progress bar - there are reported issues on video download below).

**Notes**

1. [Progress bar is not showing when downloading a video.](https://github.com/learningequality/ka-lite/issues/4430)
2. [No indicator in the topic tree for a specific video after a successful download.](https://github.com/learningequality/ka-lite/issues/4429)
3. Make sure you have no environment variable like KALITE_PYTHON (or that it's pointed correctly).
4. I'm think the Console errors are related to the issues above.

**Screenshots**
![screenshot 2015-09-21 11 06 09](https://cloud.githubusercontent.com/assets/175580/9984918/2688d3c8-6054-11e5-8ab2-59d57adebc6b.png)
![screenshot 2015-09-21 11 06 40](https://cloud.githubusercontent.com/assets/175580/9984957/0809a066-6055-11e5-8385-21d62203663c.png)


So I think the issue you have is on your OSX?  Perhaps try re-creating a virtualenv for 0.15.x branch like I did.

**Comment by 66eli77** [comment]
Thank you @cpauya  for verifying this. I verify that video download works if I'm not using virtualenv. There's some thing funny about the kalite path settings on my machine.
