### ISSUE TITLE
Fail gracefully? Or give better output?

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4564]
On `develop`.
I didn't run the `init_content_items` management command, and so I keep getting this error:

```python
Traceback (most recent call last):
  File "D:\ka-lite\python-packages\django\core\management\base.py", line 224, in
 run_from_argv
    self.execute(*args, **options.__dict__)
  File "D:\ka-lite\python-packages\django\core\management\base.py", line 263, in
 execute
    output = self.handle(*args, **options)
  File "D:\ka-lite\kalite\distributed\management\commands\setup.py", line 491, i
n handle
    call_command("annotate_content_items")
  File "D:\ka-lite\python-packages\django\core\management\__init__.py", line 161
, in call_command
    return klass.execute(*args, **defaults)
  File "D:\ka-lite\python-packages\django\core\management\base.py", line 263, in
 execute
    output = self.handle(*args, **options)
  File "D:\ka-lite\kalite\contentload\management\commands\annotate_content_items
.py", line 51, in handle
    annotate_content_models(database_path=database_path, channel=channel, langua
ge=language)
  File "D:\ka-lite\kalite\topic_tools\content_models.py", line 103, in wrapper
    output = function(*args, **kwargs)
  File "D:\ka-lite\kalite\topic_tools\content_models.py", line 398, in annotate_
content_models
    content_models = get_content_items(ids=ids, channel=channel, language=langua
ge)
  File "D:\ka-lite\kalite\topic_tools\content_models.py", line 129, in wrapper
    output = map(unparse_model_data, output.dicts())
TypeError: argument 2 to map() must support iteration
```

**Comment by benjaoming** [comment]
This pertains old json data, new content db is bundled with assessment items at the very least.
