### ISSUE TITLE
Ghost migrations when upgrading from 0.15.x to "0.16" (develop)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4600]
Looks like some migrations were added to 0.15.x that haven't made their way to develop?

```
  File "/usr/lib/python2.7/site-packages/ka_lite_static-0.16.0-py2.7.egg/kalite/distributed/management/commands/setup.py", line 384, in handle
    call_command("migrate", merge=True, verbosity=options.get("verbosity"))
  File "/usr/share/kalite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/share/kalite/dist-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/usr/share/kalite/dist-packages/south/migration/__init__.py", line 200, in migrate_app
    applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
  File "/usr/share/kalite/dist-packages/south/migration/__init__.py", line 95, in check_migration_histories
    raise exceptions.GhostMigrations(ghosts)
GhostMigrations: 

 ! These migrations are in the database but not on disk:
    <main: 0039_auto__del_assessmentitem__add_contentrating__add_unique_contentrating_>
    <main: 0040_auto__del_unique_contentrating_content_kind_content_id_user__add_uniqu>
 ! I'm not trusting myself; either fix this yourself by fiddling
```

**Comment by MCGallaspy** [comment]
Can you describe how you encountered this bug?

**Comment by radinamatic** [comment]
Hm... I'm getting a similar error while trying to run 0.15 from my repo:

1. Checked out the latest from upstream, `bin/kalite start` started the server OK, but pressing the `Login` tab did not start the modal.

2. I tried `bin/kalite manage init_content_items` but got the `Unknown command: 'init_content_items'`, so it's a 0.16 (develop) feature, right?

3. Finally, I tried:
```
didi@didi-Inspiron-3531:~/ka-lite$ bin/kalite manage setup --username=admin --password=pass --noinput
...
#### Starts the usual way, than ends up with:
...
Traceback (most recent call last):
  File "/home/didi/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/didi/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/didi/ka-lite/kalite/distributed/management/commands/setup.py", line 384, in handle
    call_command("migrate", merge=True, verbosity=options.get("verbosity"))
  File "/home/didi/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/home/didi/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/didi/.local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/didi/.local/lib/python2.7/site-packages/south/migration/__init__.py", line 200, in migrate_app
    applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
  File "/home/didi/.local/lib/python2.7/site-packages/south/migration/__init__.py", line 95, in check_migration_histories
    raise exceptions.GhostMigrations(ghosts)
GhostMigrations: 

 ! These migrations are in the database but not on disk:
    <main: 0039_auto__del_assessmentitem__add_contentrating__add_unique_contentrating_>
    <main: 0040_auto__del_unique_contentrating_content_kind_content_id_user__add_uniqu>
 ! I'm not trusting myself; either fix this yourself by fiddling
 ! with the south_migrationhistory table, or pass --delete-ghost-migrations
 ! to South to have it delete ALL of these records (this may not be good).
didi@didi-Inspiron-3531:~/ka-lite$ 

```

**Comment by MCGallaspy** [comment]
Unable to replicate. There was a similar issue (https://github.com/learningequality/ka-lite/pull/4558) where I did in fact alter the migrations. My guess is that you had a DB from before the PR was merged, ran migrations on develop, and encountered this issue.
