### ISSUE TITLE
Sql Error while downloading vidoes

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4633]
This is much less an issue than in previous releases but while downloading the entire set of videos (almost 8000) over the past 3 or 4 days which is now almost complete, I did have a single SQL error which forced me to restart the server in order to continue. I did not get a screen shot or capture of the error itself but I do have of where in the process it seemed to stall and the server.log here which I will copy below. This happened on 0.15.0 and Windows 10 and again is the only such time that I did encounter an actual error while downloading these so far, which is in itself, I think amazing! 

```
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 870, in emit
    stream.write(ufs % msg)
ValueError: I/O operation on closed file
Logged from file cronserver_blocking.py, line 34
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
Traceback (most recent call last):
  File "c:\Python27\lib\logging\__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 201
```

![2015-10-17_9-46-02](https://cloud.githubusercontent.com/assets/4349806/10562495/0df43258-751c-11e5-817f-ac572f7b1e96.png)

**Comment by benjaoming** [comment]
Since task management of downloads is now done via a JSON file and not by adding thousands of jobs to an SQLite database, we should be safe from this.

The scheduler outlined in #4907 also doesn't rely on overhead/instability from mass-transactions with a database.
