### ISSUE TITLE
Django debug toolbar not playing nice

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4658]
On `develop`, @DXCanas got the following error:

`kalite manage runserver 0.0.0.0:8008 --settings=kalite.project.settings.dev`

```python
Traceback (most recent call last):
  File "/home/dxcanas/ka-lite/python-packages/django/core/management/commands/runserver.py", line 92, in inner_run
    self.validate(display_num_errors=True)
  File "/home/dxcanas/ka-lite/python-packages/django/core/management/base.py", line 288, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/dxcanas/ka-lite/python-packages/django/core/management/validation.py", line 35, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/dxcanas/ka-lite/python-packages/django/db/models/loading.py", line 166, in get_app_errors
    self._populate()
  File "/home/dxcanas/ka-lite/python-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name)
  File "/home/dxcanas/ka-lite/python-packages/django/db/models/loading.py", line 96, in load_app
    models = import_module('.models', app_name)
  File "/home/dxcanas/ka-lite/python-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/models.py", line 5, in <module>
    from debug_toolbar import settings as dt_settings
  File "/usr/local/lib/python2.7/dist-packages/debug_toolbar/settings.py", line 8, in <module>
    from django.utils.module_loading import import_string
ImportError: cannot import name import_string
```

**Comment by MCGallaspy** [comment]
Now looking at this.

**Comment by MCGallaspy** [comment]
@DXCanas can you determine what version of django-debug-toolbar you have installed? You can check with the `pip freeze` command.
