### ISSUE TITLE
15.1 Language pack download errors.

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4727]
While testing downloading and updating language packs, I encountered several issues but I feel this one may be main repo related rather than isolated to the installer itself. This particular encounter and the following information is on ubuntu 14 LTS using the recent 15.1 build however that may be irrelevant. Expected behavior is that these packs download and install properly into the system and become available to the user. Also, that the progress bar is centered and stretches the proper width of the screen. In this case, the progress bar is roughly half the expected size and the language packs (which may be a separate issue related to https://github.com/learningequality/installers/issues/298 ) do not become available after download and are ignored on server restart as the traceback reveals. 

![2015-12-03_13-36-04](https://cloud.githubusercontent.com/assets/4349806/11574456/0bd31864-99c9-11e5-8692-b1d53eb37482.png)

```
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

INFO:kalite:Running videoscan.
INFO:kalite:Ignoring non-language pack es in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack de in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack hi in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack en in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack es in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack de in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack hi in /home/ed/.kalite/locale
INFO:kalite:Ignoring non-language pack en in /home/ed/.kalite/locale
INFO:kalite:Preloading exercise data for language en.
INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
To access KA Lite from another connected computer, try the following address(es):
        http://10.0.2.15:8008/
To access KA Lite from this machine, try the following address:
        http://127.0.0.1:8008/

Going to daemon mode, logging to /home/ed/.kalite/server.log
```

**Comment by EdDixon** [comment]
Now known to be a problem on all desktop platforms (Linux, MAC, and Windows) using the 0.15.1 build.

**Comment by EdDixon** [comment]
Moving info and errors from installers to here to help in troubleshooting the problem:

Original report: On Ubuntu 14 LTS testing the recent 15.1 installations (not upgrade) the following error is encountered when trying to update or install language packs both through UI and manually using the kalite command. Replicated by @aronasorman 
![2015-12-03_13-15-28](https://cloud.githubusercontent.com/assets/4349806/11574110/e30e8028-99c6-11e5-894a-ce1a340b36e1.png)

```
ed@ed-VirtualBox:~$ kalite manage languagepackdownload -lde --commandline
INFO:kalite:Downloading language pack for lang_name=Deutsch, software_version=0.15
INFO:kalite:Downloading language pack 'de'
INFO:kalite:Retrieving language pack: de
INFO:kalite:Unpacking language pack 'de'
INFO:kalite:Unpacking new translations
WARNING:py.warnings:/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py:142: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise type(e), type(e)(e.message + _("Language pack corrupted. Please try downloading the language pack again in a few minutes."))

INFO:kalite:Error: File is not a zip fileLanguage pack corrupted. Please try downloading the language pack again in a few minutes.
INFO:kalite:Cancelling process languagepackdownload
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/fle_utils/chronograph/management/croncommand.py", line 38, in execute
    super(CronCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py", line 85, in handle
    unpack_language(lang_code, zip_filepath=zip_filepath)
  File "/usr/lib/python2.7/dist-packages/kalite/updates/management/commands/languagepackdownload.py", line 142, in unpack_language
    raise type(e), type(e)(e.message + _("Language pack corrupted. Please try downloading the language pack again in a few minutes."))
BadZipfile: File is not a zip fileLanguage pack corrupted. Please try downloading the language pack again in a few minutes.
ed@ed-VirtualBox:~$ 
```

**Comment by EdDixon** [comment]
From what I can tell all these issues are now resolved (even the progress bars) after a server side fix. On the same Ubuntu 14 LTS installation I did not encounter these issues today. CLosing for now unless they should reappear...

**Comment by benjaoming** [comment]
Yay :)
