### ISSUE TITLE
content_rating BDD test randomly failing

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4736]
```
Took 1m9.421s
.Feature: Content Rating # kalite/distributed/features/content_rating.feature:1
  Tests for the content rating form/widget, which should appear on content pages (video, exercises, etc)
  @as_learner
  Scenario: User rates an unrated item  # kalite/distributed/features/content_rating.feature:5
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:19
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:19 1.455s
    Then I see a feedback form          # kalite/distributed/features/steps/content_rating.py:38
    Then I see a feedback form          # kalite/distributed/features/steps/content_rating.py:38 0.700s
    When I fill out the form            # kalite/distributed/features/steps/content_rating.py:108
    When I fill out the form            # kalite/distributed/features/steps/content_rating.py:108 1.903s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 110, in impl
          enter_star_ratings(context)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 161, in enter_star_ratings
          rate_id(context, id_)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 182, in rate_id
          WebDriverWait(context.browser, 10).until(rate_element)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 66, in until
          value = method(self._driver)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 176, in rate_element
          rating_el = [el for el in els if int(el.get_attribute("data-val")) == val].pop()
      IndexError: pop from empty list
```

**Comment by benjaoming** [comment]
Hurray!
