### ISSUE TITLE
No matching distribution found for django-tastypie==0.12.2dev0

### ISSUE THREAD

**Issue by amodia** [learningequality/ka-lite#4752]
**Branch:** `develop`
**Current behavior:** When running `make dist` command it will spawn this error:
```
python setup.py sdist --formats=gztar,zip --static
This is a static build... invoking pip to put static dependencies in dist-packages/
No handlers could be found for logger "pip.index"
Traceback (most recent call last):
  File "<pyrun>/pyrun2.7.py", line 823, in <module>
  File "<pyrun>/pyrun2.7.py", line 699, in pyrun_execute_script
  File "setup.py", line 307, in <module>
    install_distributions(STATIC_REQUIREMENTS)
  File "setup.py", line 301, in install_distributions
    command.run(opts, distributions)
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/richard/installers/osx/temp/pyrun-2.7/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django-tastypie==0.12.2dev0
make: *** [dist] Error 1
.. Abort!  Error/s encountered running 'make dist'.
```

The build server on OS X installer will fail because of this error.

/cc: @benjaoming

**Comment by arceduardvincent** [comment]
Hi @benjaoming and @cpauya I found out some hints in this issue. 
We are trying to invoke pip to put static dependencies in ` dist-packages/` however it is failing to get output from pip.

It was successfully installed if I used pip install in my virtualenv.
```python
Collecting django-tastypie-0.12.2dev0 from https://github.com/django-tastypie/django-tastypie/archive/e6bc34bea83d53552c7fc9dfa696ed7693fe22ab.zip#egg=django-tastypie-0.12.2dev0 (from -r requirements.txt (line 18))
  Downloading https://github.com/django-tastypie/django-tastypie/archive/e6bc34bea83d53552c7fc9dfa696ed7693fe22ab.zip (329kB)
    100% |████████████████████████████████| 331kB 471kB/s 
```
When I try to get the output and write it on the `dist-packages/`. I used `make dist`.
I notice that the `DEPENDENCY_LINKS` where present but it fail to get the output from pip. Instead it tells me that `No matching distribution found for django-tastypie==0.12.2dev0`

```python
python setup.py sdist --formats=gztar,zip --static
>>>>>>> DIST_REQUIREMENTS: [u'docopt>=0.6,<0.7', u'South==1.0.2', u'django-js-reverse==0.5.0', u'ply==3.4', u'slimit==0.8.1', u'six==1.9.0', u'django-appconf==1.0.1', u'peewee==2.6.3', u'python-dateutil==2.4.2', u'django-dbbackup==2.3.2', u'django-annoying==0.8.4', u'cherrypy==3.2.2', u'ifcfg==0.9.2', u'importlib==1.0.3', u'pbkdf2==1.3', u'rsa==3.1.1', u'youtube-dl==2015.11.24', u'django-tastypie==0.12.2dev0']
>>>>>>> DEPENDENCY_LINKS: [u'https://github.com/django-tastypie/django-tastypie/archive/e6bc34bea83d53552c7fc9dfa696ed7693fe22ab.zip#egg=django-tastypie-0.12.2dev0']
This is a static build... invoking pip to put static dependencies in dist-packages/
No handlers could be found for logger "pip.index"
Traceback (most recent call last):
  File "setup.py", line 311, in <module>
    install_distributions(STATIC_REQUIREMENTS)
  File "setup.py", line 305, in install_distributions
    command.run(opts, distributions)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/echoair/.virtualenvs/kalite_dist/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django-tastypie==0.12.2dev0
make: *** [dist] Error 1
```

**Comment by benjaoming** [comment]
Annoying, sorry about that. There's some more background on the choice in #3825 and #4689 -- the issue is that the releases of tastypie aren't working with django 1.5, only the current master is.

I'll work out why it fails.

But you know, `python setup.py install` works fine on a blank virtualenv. And `pip install -e .`. It's the generation of the sidst with static dependencies that's broken.

**Comment by benjaoming** [comment]
Accepting the blame for this :)

**Comment by arceduardvincent** [comment]
Thanks for the heads up sir.

I will try what you suggested :)

**Comment by amodia** [comment]
Hi @benjaoming any updates on this?

**Comment by benjaoming** [comment]
Note, this also affects `pip install -e .`.

**Comment by benjaoming** [comment]
Apparently pip ignores the dependency links so the latest master of tastypie is not installed. Fix for editable install:

    pip install --process-dependency-links -e .

Will see how we can fix this, clearly it's not nice to have to enforce such a quirk.
