### ISSUE TITLE
Instructions for PPA that work on Raspberry Pi

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4792]
Current instructions use `add-apt-repository`, however the command is quicky on Debian and fails completely on Raspbian because software-properties-common doesn't come preloaded with any mention of Raspbian:

```
# ...

   you only need to bring the .deb version of this to use in offline 
   environments. DO NOT INSTALL THIS VIA THE PPA, UPDATES WILL BE 350+ MB 
   EACH!!
 More info: https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite
Press [ENTER] to continue or ctrl-c to cancel adding it

<aptsources.sourceslist.SourcesList object at 0x76217dd0>
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
```

Need to change this to universal instruction:

```bash
sudo echo "deb http://ppa.launchpad.net/learningequality/ka-lite/ubuntu trusty main" >> /etc/apt/sources.list.d/learningequality-ka-lite-trusty.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 74F88ADB3194DD81
```

**Comment by rtibbles** [comment]
Fixed in #4794
