### ISSUE TITLE
ConnectionDoesNotExist error when taking new screenshots for docs

### ISSUE THREAD

**Issue by manipalsingh013** [learningequality/ka-lite#4862]
While grabbing new screenshots in version **0.16.0** on **ubuntu 14.04** **ConnectionDoesNotExis**t error appeared.

Steps to reproduce:
**cd docs
SPHINX_SS_USE_PVD=true make SPHINXOPTS="-D screenshots_create=1" html**

Output:

sphinx-build -b html -d _build/doctrees  -D screenshots_create=1 . _build/html
Running Sphinx v1.3.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] developer_docs/index  
Traceback (most recent call last):
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(_args, *_options.__dict__)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(_args, *_options)
  File "/home/manipalsingh/ka-lite/kalite/distributed/management/commands/screenshots.py", line 69, in handle
    sc = Screenshot(**options)
  File "/home/manipalsingh/ka-lite/kalite/distributed/management/commands/screenshots.py", line 202, in **init**
    self.admin_user = reset_sqlite_database(self.admin_username, self.admin_email, self.default_password, verbosity=self.verbosity)
  File "/home/manipalsingh/ka-lite/kalite/distributed/management/commands/screenshots.py", line 97, in reset_sqlite_database
    call_command("syncdb", interactive=False, stdout=new_io, router=router, verbosity=verbosity, database="assessment_items")
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/**init**.py", line 161, in call_command
    return klass.execute(_args, *_defaults)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(_args, *_options)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 393, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
    syncdb.Command().execute(**options)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(_args, *_options)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/base.py", line 393, in handle
    return self.handle_noargs(**options)
  File "/home/manipalsingh/ka-lite/python-packages/django/core/management/commands/syncdb.py", line 55, in handle_noargs
    connection = connections[db]
  File "/home/manipalsingh/ka-lite/python-packages/django/db/utils.py", line 91, in **getitem**
    self.ensure_defaults(alias)
  File "/home/manipalsingh/ka-lite/python-packages/django/db/utils.py", line 75, in ensure_defaults
    raise ConnectionDoesNotExist("The connection %s doesn't exist" % alias)
ConnectionDoesNotExist: The connection assessment_items doesn't exist

Exception occurred:
  File "/home/manipalsingh/ka-lite/docs/screenshot.py", line 70, in process_screenshots
    raise Exception("Screenshot process had nonzero return code: {0}".format(subprocess.returncode))
Exception: Screenshot process had nonzero return code: 1
The full traceback has been saved in /tmp/sphinx-err-fV9tnl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
make: **\* [html] Error 1

**Comment by benjaoming** [comment]
Fixed in #5047
