### ISSUE TITLE
AssertionError at /api/videolog/ for Admin users

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4878]
## Summary

After fetching the latest upstream today, at first login as Admin user I could load and play videos ok, but as soon as they finished, the following error kept appearing:

```
Unexpected error; contact the FLE with the following information: 500
There was an unexpected error!
[object Object]
```

However, the error did not appear once I logged out and re-logged in as Learner, nor it appeared when I logged in again as Admin. I re-tested this sequence (admin-error, learner-no-error, admin no-error) with 3 separate videos, and it appeared consistent. 

## Branch

0.16 in FF on Mac OSX

## Traceback

```
[21/Feb/2016 04:40:20] "GET /static/js/distributed/bundles/bundle_video.js HTTP/1.1" 200 237475
[21/Feb/2016 04:40:20] "GET /content/y2-uaPiyoxc.mp4 HTTP/1.1" 200 593814
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
[21/Feb/2016 04:40:20] "GET /content/y2-uaPiyoxc.mp4 HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50589)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/servers/basehttp.py", line 150, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
[21/Feb/2016 04:40:20] "GET /static/css/distributed/font/vjs.woff HTTP/1.1" 200 2508
[21/Feb/2016 04:40:21] "GET /content/y2-uaPiyoxc.mp4 HTTP/1.1" 200 2526364
[21/Feb/2016 04:41:34] "POST /api/videolog/ HTTP/1.1" 500 8362
```

Console output
```
Response text: AssertionError at /api/videolog/
User ID required for get_uuid

Request Method: POST
Request URL: http://127.0.0.1:8000/api/videolog/
Django Version: 1.5.1
Python Executable: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Python Version: 2.7.11
Python Path: ['/Users/didim/LE/ka-lite/python-packages', '/Users/didim/LE/ka-lite/dist-packages', '/Users/didim/LE/ka-lite/kalite', '/Users/didim/LE/ka-lite', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',[…] bundle_common.js:27596:17
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack trace:
require<[298]</</jQuery.parseJSON@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:55839:9
handleFailedAPI@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:27590:28
require<[42]</Backbone.ajax/<@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:24431:13
require<[298]</</jQuery.Callbacks/fire@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:51416:10
require<[298]</</jQuery.Callbacks/self.fireWith@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:51528:7
done@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:56583:1
require<[298]</</</<.send/callback/<@http://127.0.0.1:8000/static/js/distributed/bundles/bundle_common.js:56922:1
 bundle_common.js:27597:17

```
## How to reproduce

1. Login as Admin 
1. Pick a video from sidebar
1. Play video 'till the end

## Screenshots

![object_videolog_error](https://cloud.githubusercontent.com/assets/1457929/13200874/1b9262ca-d85b-11e5-89c3-571789919769.png)

**Comment by shubhsingh594** [comment]
can i take this ?

**Comment by radinamatic** [comment]
Same as #4910, non extant on Alpha4 deb on Ubuntu & build 150 on W7. let's concentrate on more pressing issues.

**Comment by MCGallaspy** [comment]
If I'm understanding correctly, it's been resolved.
