### ISSUE TITLE
No progress bar on language pack download

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4914]
## Summary

After the #4909 was merged, progress bar works fine on video download, but is still not displayed during the language packs download. 

Language pack does seem to be downloaded after a while, can be set as default, but switching Learner to Spanish gives `no such column: t1.sort_order` error (see screenshot below). No JS errors whatsoever in the console, see the traceback for details.

## Branch or installer method

Branch: latest 0.16

## Traceback or relevant snippet from server.log

```
[INFO] [2016-02-25 01:15:32,389] django.request: HTTP Request /api/languagepacks/start - Response: 200
[25/Feb/2016 01:15:32] "POST /api/languagepacks/start HTTP/1.1" 200 72
[25/Feb/2016 01:15:32] "GET /api/updates/progress?process_name=languagepackdownload&_=1456359285734 HTTP/1.1" 200 2
[INFO] [2016-02-25 01:15:32,465] kalite: Downloading content pack.
[25/Feb/2016 01:15:34] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285735 HTTP/1.1" 200 2
[25/Feb/2016 01:15:36] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285736 HTTP/1.1" 200 2
[25/Feb/2016 01:15:38] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285737 HTTP/1.1" 200 2
[25/Feb/2016 01:15:40] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285738 HTTP/1.1" 200 2
[INFO] [2016-02-25 01:15:41,904] kalite: Moving content files to the right place.
[25/Feb/2016 01:15:42] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285739 HTTP/1.1" 200 2
[WARNING] [2016-02-25 01:15:42,465] kalite: No es-ES_icu.js file found in locale_path /Users/didim/LE/ka-lite/locale/
[INFO] [2016-02-25 01:15:42,465] kalite: Writing i18nized js file to /Users/didim/LE/ka-lite/content/locale/js/i18n/es-ES.js
[INFO] [2016-02-25 01:15:43,189] kalite: Looking for available content items.
[INFO] [2016-02-25 01:15:43,289] kalite: Annotating content for language: es-ES, channel: khan
[ERROR] [2016-02-25 01:15:43,292] kalite: No content database file found
Process CommandProcess-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 61, in run
    call_command(self.cmd, *self.args, **self.kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 88, in handle
    self.download(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 101, in download
    self.process_content_pack(zf, lang)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 126, in process_content_pack
    call_command("annotate_content_items", language=lang)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/management/commands/annotate_content_items.py", line 43, in handle
    annotate_content_models(database_path=database_path, channel=channel, language=language)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 133, in wrapper
    output = function(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 655, in annotate_content_models
    for path, update in content_models:
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 560, in iterator_content_items
    items = Item.select().dicts().iterator()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2797, in iterator
    return iter(self.execute().iterator())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2787, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2470, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.sort_order
[25/Feb/2016 01:15:44] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285740 HTTP/1.1" 200 2
[25/Feb/2016 01:15:46] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285741 HTTP/1.1" 200 2
```

![bienvenidospanishlearner](https://cloud.githubusercontent.com/assets/1457929/13306113/16969a08-db61-11e5-8b45-adb3e1f4f84c.png)

**Comment by aronasorman** [comment]
Two bugs here:
1. Progress bar is still not showing for language packs
2. Language pack content DBs need to be updated.

**Comment by aronasorman** [comment]
Focusing on #2 bug today, as it will take a bit of work. Here's what I plan on doing:

Right now we build language packs with the `--no-assessment-items` flag. That avoids fetching both assessment item metadata and resources. However, this will cause the content db to not include any assessment item data.

So now we need to introduce another flag, `--no-assessment-resources`, which makes the content pack maker fetch the metadata, but not the files.

I would then need to have the build server build language packs.

**Comment by radinamatic** [comment]
@aronasorman If it helps any, right before the above traceback, I installed (freshly downloaded) `en.zip` locally:

```
Didis-Mac-mini:ka-lite didim$ bin/kalite manage retrievecontentpack local en en.zip 
[WARNING] [2016-02-25 00:52:14,998] kalite: Channel khan does not exist.
[INFO] [2016-02-25 00:52:15,216] kalite: Cancelling process retrievecontentpack
[INFO] [2016-02-25 00:52:15,225] kalite: Installing a local content pack.
[INFO] [2016-02-25 00:52:15,542] kalite: Moving content files to the right place.
[WARNING] [2016-02-25 00:52:15,629] kalite: No en_icu.js file found in locale_path /Users/didim/LE/ka-lite/locale/
[INFO] [2016-02-25 00:52:15,629] kalite: Writing i18nized js file to /Users/didim/LE/ka-lite/content/locale/js/i18n/en.js
[INFO] [2016-02-25 00:55:08,870] kalite: Looking for available content items.
[INFO] [2016-02-25 00:55:09,614] kalite: Annotating content for language: en, channel: khan
[INFO] [2016-02-25 00:55:21,220] kalite: Annotation complete for language: en, channel: khan
[INFO] [2016-02-25 00:55:21,220] kalite: Finished processing content pack.
Didis-Mac-mini:ka-lite didim$ bin/kalite manage runserver --settings=kalite.project.settings.dev
Starting browserify
Browserify process on pid 1399
Validating models...

[WARNING] [2016-02-25 01:04:32,863] kalite: Channel khan does not exist.
0 errors found
February 25, 2016 - 01:04:36
Django version 1.5.1, using settings 'kalite.project.settings.dev'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watchify: Found 19 bundles, compiling.
Watchify: Assuming that Khan Util files are already deAMDified
Watchify: Starting watcher
Watchify: 4552036 bytes written (18.04 seconds)
Watchify: 19 Bundles written.
[25/Feb/2016 01:05:15] "GET /static/images/distributed/favicon.ico HTTP/1.1" 200 946
```

**Comment by aronasorman** [comment]
Thanks! Looks like it's working OK. My hunch is for bug number 1, that the progress log entries aren't being recorded somehow. I'll look into that once I have the language packs building.

**Comment by aronasorman** [comment]
Update: I've got non-english content packs building again. However, dubbed videos are missing from Amara. Turns out it's returning a 404 for the spanish videos: 

https://www.amara.org/api/videos/q9L5sggiQoH7/languages/es-ES/subtitles/?format=vtt

**Comment by aronasorman** [comment]
But it does return something for `en`:

https://www.amara.org/api/videos/q9L5sggiQoH7/languages/en/subtitles/?format=vtt

Weirdly enough, it doesn't return a vtt for a lot of languages I've tried: `de, pt, zh, fr`.

**Comment by radinamatic** [comment]
Is there something we need to enable on Amara, in order to get these subs in VTT format, or it's supposed to grab them on a fly? I never had to use the API before...

**Comment by aronasorman** [comment]
@radinamatic looks like we need to use an API key. I'm seeing if that solves our problems here.

**Comment by radinamatic** [comment]
:+1:

**Comment by aronasorman** [comment]
Still returning 'not found'.

**Comment by aronasorman** [comment]
By logging in to AMARA, https://www.amara.org/api/videos/q9L5sggiQoH7/languages/ now gives me a list of available languages. You can see the JSON returned here: https://gist.github.com/aronasorman/e6e26a16215983a73815

I won't act on this new information right now. My next step is to extend `retrieve_subtitles` to be able to pass the API key. We can then see if we can get at least some subtitles out of everything we downloaded.

**Comment by aronasorman** [comment]
Updates using my local `es-ES` content pack:

![screen shot 2016-02-29 at 10 20 13](https://cloud.githubusercontent.com/assets/191955/13404355/18611104-dece-11e5-8948-c404f4a6191e.png)
![screen shot 2016-02-29 at 10 20 18](https://cloud.githubusercontent.com/assets/191955/13404356/1861ddaa-dece-11e5-95fd-56dca2a167a1.png)

Exercises work, but alas no images are appearing. In the meantime I'll try to get this uploaded somewhere @radinamatic, so you can begin testing it!

**Comment by radinamatic** [comment]
Sweet sight to my sore (almost) Spanish eyes, @aronasorman! :+1:

**Comment by aronasorman** [comment]
I tried downloading a dubbed video, sadly it wasn't appearing in the topic tree. Yet another bug!

**Comment by radinamatic** [comment]
(this is on my dev repo, I'm gonna test this on a VM now, unless there's a more pressing matter)

Sidebar: confirmed!
Exercise: confirmed!
Images (hints): I know you are working on it ;)

![img-hint-error-pedazo-queso](https://cloud.githubusercontent.com/assets/1457929/13406185/6cb43b56-df22-11e5-87dd-fb248a85d7d0.png)

(I couldn't resist add in this pic, "pedazos de queso" in Spain would mean "really big chunks of cheese") :grinning:

**Comment by aronasorman** [comment]
Good news! 

![screen shot 2016-02-29 at 12 35 39](https://cloud.githubusercontent.com/assets/191955/13408133/04e119a4-dee1-11e5-85a6-5f2a7b8de34a.png)

This fix is on the language pack. Uploading a new one in the dev room in a bit.

**Comment by radinamatic** [comment]
Build 154 on Windows 7, with the new `es-ES.zip`:

Sidebar: confirmed!
Exercise: confirmed!
Images (hints): (as ob above, seems soon) :wink: 

But I can actually see the video topic tree in Spanish, only **when the default UI language is set to it**. In 0.15 video topic tree used to appear localized when selecting videos in languages different from English. So this remain to be fixed.

**Comment by aronasorman** [comment]
Ah I see. This is in the video download page, not in the tropic tree? Let's wait for the bunch-o-fixes PR that @rtibbles, and see if it's still extant after that.

**Comment by radinamatic** [comment]
Sorry, yes, when I say "topic tree" I refer to one that appear on video download page...

**Comment by radinamatic** [comment]
¡Qué zorritos más bonitos! @aronasorman 

![zorros-bonitos](https://cloud.githubusercontent.com/assets/1457929/13408819/14abf5bc-df30-11e5-91a1-c40ed9266521.png)

**Comment by radinamatic** [comment]
Fixed, closing!
