### ISSUE TITLE
Donwloading French language pack gets Chinese instead

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4930]
## Summary

At first I thought the error was mine while selecting language from the dropdown, but then after restart I saw Chinese (!!!) among available languages. When I switch language to that Chinese as Learner, I get the infamous `no such table item` error (1st screenshot), and in `.kalite/locale` folder I can see the FR folder (2nd screenshot).

## Branch or installer method

Happened first on build 66 for OSX, but seeing the same on branch 0.16

## Traceback or relevant snippet from server.log

```
[INFO] [2016-02-26 21:10:30,844] django.request: HTTP Request /api/languagepacks/start - Response: 200
[26/Feb/2016 21:10:30] "POST /api/languagepacks/start HTTP/1.1" 200 92
[26/Feb/2016 21:10:30] "GET /api/updates/progress?process_name=languagepackdownload&_=1456517251910 HTTP/1.1" 200 2
[INFO] [2016-02-26 21:10:30,937] kalite: Cancelling process retrievecontentpack
[INFO] [2016-02-26 21:10:31,065] kalite: Downloading content pack.
[26/Feb/2016 21:10:32] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251911 HTTP/1.1" 200 2
[26/Feb/2016 21:10:34] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251912 HTTP/1.1" 200 2
[26/Feb/2016 21:10:36] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251913 HTTP/1.1" 200 2
[26/Feb/2016 21:10:38] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251914 HTTP/1.1" 200 2
[26/Feb/2016 21:10:40] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251915 HTTP/1.1" 200 2
[26/Feb/2016 21:10:42] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251916 HTTP/1.1" 200 2
[26/Feb/2016 21:10:44] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251917 HTTP/1.1" 200 2
[26/Feb/2016 21:10:46] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251918 HTTP/1.1" 200 2
[INFO] [2016-02-26 21:10:47,777] kalite: Moving content files to the right place.
[WARNING] [2016-02-26 21:10:48,120] kalite: No fr_icu.js file found in locale_path /Users/didim/LE/ka-lite/locale/
[INFO] [2016-02-26 21:10:48,120] kalite: Writing i18nized js file to /Users/didim/LE/ka-lite/content/locale/js/i18n/fr.js
[INFO] [2016-02-26 21:10:48,474] kalite: Looking for available content items.
[INFO] [2016-02-26 21:10:48,885] kalite: Annotating content for language: fr, channel: khan
[ERROR] [2016-02-26 21:10:48,887] kalite: No content database file found
[26/Feb/2016 21:10:48] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251919 HTTP/1.1" 200 2
Process CommandProcess-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 61, in run
    call_command(self.cmd, *self.args, **self.kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 88, in handle
    self.download(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 101, in download
    self.process_content_pack(zf, lang)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 126, in process_content_pack
    call_command("annotate_content_items", language=lang)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/management/commands/annotate_content_items.py", line 43, in handle
    annotate_content_models(database_path=database_path, channel=channel, language=language)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 133, in wrapper
    output = function(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 655, in annotate_content_models
    for path, update in content_models:
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 560, in iterator_content_items
    items = Item.select().dicts().iterator()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2797, in iterator
    return iter(self.execute().iterator())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2787, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2470, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.sort_order
[26/Feb/2016 21:10:50] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251920 HTTP/1.1" 200 2
[26/Feb/2016 21:10:52] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-26T20:10:30.000Z&_=1456517251921 HTTP/1.1" 200 2
```

## How to reproduce

1. Download French language pack.
1. Restart server.
1. Try to switch the UI language.

## Screenshots

![fr-forzh-_yosemite_10_10_5](https://cloud.githubusercontent.com/assets/1457929/13374945/51288c2e-dd93-11e5-9c27-11d586e4d50a.png)

![fr-forzh-2_yosemite_10_10_5](https://cloud.githubusercontent.com/assets/1457929/13374966/da55ba44-dd93-11e5-88c5-e9a020ae574d.png)

**Comment by aronasorman** [comment]
Please see if this is still the case by downloading `fr` manually: http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/fr.zip

and then installing it locally. Have not made `fr` available for download yet. Once this bug is confirmed fix I'll reopen it for download.

**Comment by radinamatic** [comment]
Ok, working on Win7 with build 165 and latest contentpacks, will check it out!

**Comment by radinamatic** [comment]
@aronasorman  Seems to be fixed with locally installed fr.zip! :+1:

**Comment by radinamatic** [comment]
I am getting errors while downloading & scanning for videos in French, though...

![fr1](https://cloud.githubusercontent.com/assets/1457929/13476728/761f0ef2-e0c9-11e5-8f1d-6d10c2e52f29.png)

![fr2](https://cloud.githubusercontent.com/assets/1457929/13476737/821d7b94-e0c9-11e5-8826-2093e3be1d2c.png)

Separate issue, @aronasorman?

**Comment by aronasorman** [comment]
Yeah, seems like the woff2 issue that @rtibbles fixed. Why did it reappear
again though? Is it only happening for French?

**Comment by radinamatic** [comment]
I don't think that's the issue, those errors still appear all around... :unamused: 

See the `Erreur pendant mise à jour` alert message? That seems to be the problem only while downloading videos in French!

**Comment by aronasorman** [comment]
Is it causing any other error? Are video downloads failing?

**Comment by aronasorman** [comment]
Anyway, the issue is solved. Please file another issue regarding the `Erreur pendant mise à jour` alert message.
