### ISSUE TITLE
Errors downloading videos in French

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4953]
## Summary

Fixed #4930, French UI works OK, but problems arise with video download and scanning.

## Branch or installer method

Beta1 on Ubuntu.

## Traceback or relevant snippet from server.log

```
[INFO] [2016-03-02 23:43:10,986] kalite: Téléchargement de 'Compter de un en un'
[ERROR] [2016-03-02 23:43:14,496] root: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/hMlnp_LjDbM.mp4/hMlnp_LjDbM.png
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/fle_utils/videos.py", line 51, in download_video
    raise URLNotFound("Thumbnail was not found, tried: {}".format(thumb_url))
URLNotFound: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/hMlnp_LjDbM.mp4/hMlnp_LjDbM.png
[ERROR] [2016-03-02 23:43:16,265] kalite: No content database file found
[INFO] [2016-03-02 23:43:16,275] kalite: Erreur lors du téléchargement de hMlnp_LjDbM : attempt to write a readonly database ; passage à la prochaine vidéo.
[WARNING] [2016-03-02 23:43:16,287] kalite: Tried to remove hMlnp_LjDbM from file queue but found kujXvvdVMx0 instead.
[INFO] [2016-03-02 23:43:17,019] kalite: Téléchargement de 'Compter dans l'ordre'
[ERROR] [2016-03-02 23:43:23,519] root: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/kujXvvdVMx0.mp4/kujXvvdVMx0.png
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/fle_utils/videos.py", line 51, in download_video
    raise URLNotFound("Thumbnail was not found, tried: {}".format(thumb_url))
URLNotFound: Thumbnail was not found, tried: http://kalite.learningequality.org/download/videos/kujXvvdVMx0.mp4/kujXvvdVMx0.png
[ERROR] [2016-03-02 23:43:26,367] kalite: No content database file found
[INFO] [2016-03-02 23:43:26,374] kalite: Erreur lors du téléchargement de kujXvvdVMx0 : attempt to write a readonly database ; passage à la prochaine vidéo.
[WARNING] [2016-03-02 23:43:26,380] kalite: Tried to remove kujXvvdVMx0 from file queue, but was empty instead.
[INFO] [2016-03-02 23:43:26,380] kalite: 2 de 4 vidéos téléchargées.
```

## How to reproduce

1. Install French languagepack
1. Try to download a few videos.

## Screenshots

Download:
![fr1](https://cloud.githubusercontent.com/assets/1457929/13476728/761f0ef2-e0c9-11e5-8f1d-6d10c2e52f29.png)

Scanning:
![fr2](https://cloud.githubusercontent.com/assets/1457929/13476737/821d7b94-e0c9-11e5-8826-2093e3be1d2c.png)

Seems to be a problems with some missing thumbnails, @aronasorman?

**Comment by radinamatic** [comment]
I'm not seeing this issue on build 76 with Yosemite, and not sure when/which PR addressed it...  
Latest French contenpack installed locally. Will wait for the next .deb installer to re-test and close.

**Comment by radinamatic** [comment]
Non extant on Beta2 .deb installer in Ubuntu. Closing!
