### ISSUE TITLE
IndexError: tuple index out of range - installing languagepacks with dash

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4954]
## Summary

All is well when using the `kalite shell`, but there used to be a "gentle" message to inform of this problem when running the `kalite manage retrievecontentpack local` on these packs. Now it throws an ugly red error

## Branch or installer method
Beta1 on Ubuntu.

## Traceback or relevant snippet from server.log

```
didi@didi-virtualbox:~/Desktop$ sudo kalite manage retrievecontentpack local es-ES es-ES.zip 
[WARNING] [2016-03-02 21:56:06,156] kalite: Channel khan does not exist.
[INFO] [2016-03-02 21:56:06,198] kalite: Cancelling process retrievecontentpack
[INFO] [2016-03-02 21:56:06,237] kalite: Installing a local content pack.
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/management/commands/retrievecontentpack.py", line 91, in handle
    self.local(*args, **options)
  File "/usr/lib/python2.7/dist-packages/kalite/distributed/management/commands/retrievecontentpack.py", line 107, in local
    zippath = args[2]
IndexError: tuple index out of range
```

@aronasorman

**Comment by radinamatic** [comment]
Confirmed the same error on OSX El Capitan.

**Comment by aronasorman** [comment]
Ah, I encountered this error before. It's when there's a `-` in the zip name. Can you rename you zipfile to `es.zip` and see if it works?

**Comment by radinamatic** [comment]
I sure can, but the version of contentpacks from a few days ago displayed an-actual-sentence-message informing the user not to use dashes (#4935):

```
Please only use --option=value or -x123 patterns. No spaces allowed between option and value. The option parser gets confused if you do otherwise.

Will be fixed in a future release.
```

This got lost somewhere and now the user is getting an error code message.

**Comment by MCGallaspy** [comment]
Indeed, the dash issue should have been resolved: https://github.com/learningequality/ka-lite/pull/4939

**Comment by MCGallaspy** [comment]
It's a bug in `update_default_args` -- now working on it.
