### ISSUE TITLE
kalite diagnose not working

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#4974]
```
# aron at ubuntu in ~/src/github.com/aronasorman/ka-lite on git:i18n-fixes x [14:25:11]
$ bin/kalite diagnose

KA Lite diagnostics

Calculating diagnostics...

Traceback (most recent call last):
  File "/home/aron/src/github.com/aronasorman/ka-lite/kalitectl.py", line 948, in <module>
    diagnose()
  File "/home/aron/src/github.com/aronasorman/ka-lite/kalitectl.py", line 773, in diagnose
    diag("assessment database", settings.DATABASES['assessment_items']['NAME'])
KeyError: 'assessment_items'
[288275 refs]
[22848 refs]
(ka-lite)
```

**Comment by jamalex** [comment]
Fix has been merged.
