### ISSUE TITLE
loose-envify

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#4983]
## Summary

Doing `make assets`, which runs `npm install --production` breaks because of a missing `loose-envify` package.

## Branch or installer method

 - Branch: 0.16.x

## Traceback or relevant snippet from server.log

```
8:10:54 PM - me: (kalite)kalitebuilder@overtag:~/ka-lite$ make assets
# Necessary because NPM may have wrong versions in the cache
npm cache clean
npm install --production
npm WARN package.json ka-lite@0.0.0 license should be a valid SPDX license expression
node build.js
Watchify: Found 19 bundles, compiling.
Watchify: Assuming that Khan Util files are already deAMDified
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'loose-envify' from '/home/kalitebuilder/ka-lite/node_modules/react/node_modules/fbjs'
    at /home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
make: *** [assets] Error 1
```

## How to reproduce

Clean your git checkout or do a fresh clone and run `make assets`.

**Comment by rtibbles** [comment]
Not sure I understand why this is missing. It's in the package.json of the package that is requesting it.

Is there a stack trace from the npm install itself that might explain why it wasn't installed?

**Comment by rtibbles** [comment]
(Note: this is not directly required by our code, but is a dependency of a dependency).

**Comment by MCGallaspy** [comment]
Hm, I just had a similar experience when trying to `require` a dependency of a dependency. Let me look in to it.

**Comment by MCGallaspy** [comment]
Unable to replicate... Could it be version dependent? Here's mine:
```txt
(develop-0-16) D:\ka-lite>npm --version
2.14.20

(develop-0-16) D:\ka-lite>node --version
v4.4.0
```
