### ISSUE TITLE
generaterealdata is broken

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4985]
## Summary

"kalite manage generaterealdata" not working

## Branch or installer method

-OS: Mac

 - Branch: develop 0.16.x

## Traceback or relevant snippet from server.log

```
Traceback (most recent call last):
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/Eli/Desktop/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/Eli/Desktop/ka-lite/kalite/coachreports/management/commands/generaterealdata.py", line 501, in handle
    handler(*args, **options)
  File "/Users/Eli/Desktop/ka-lite/kalite/coachreports/management/commands/generaterealdata.py", line 556, in handle_stuff
    generate_fake_exercise_logs(facility_user=facility_users)
  File "/Users/Eli/Desktop/ka-lite/kalite/coachreports/management/commands/generaterealdata.py", line 221, in generate_fake_exercise_logs
    (elogs, ulogs) = generate_fake_exercise_logs(facility_user=user, topics=[topic], start_date=start_date)
  File "/Users/Eli/Desktop/ka-lite/kalite/coachreports/management/commands/generaterealdata.py", line 238, in generate_fake_exercise_logs
    exercises = get_topic_contents(topic_id=topic, kinds=["Exercise"])
  File "/Users/Eli/Desktop/ka-lite/kalite/topic_tools/content_models.py", line 153, in wrapper
    output = function(*args, **kwargs)
  File "/Users/Eli/Desktop/ka-lite/kalite/topic_tools/content_models.py", line 128, in wrapper
    output = function(*args, **kwargs)
  File "/Users/Eli/Desktop/ka-lite/kalite/topic_tools/content_models.py", line 390, in get_topic_contents
    topic_node = Item.get(Item.id == topic_id, Item.kind == "Topic")
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 4138, in get
    return sq.get()
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 2740, in get
    return clone.execute().next()
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 2787, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 2470, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Users/Eli/Desktop/ka-lite/dist-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such table: item
```

**Comment by rtibbles** [comment]
Do you have a content database installed?

**Comment by 66eli77** [comment]
and I see a folder called content_databases with content_khan_en.sqlite in it

**Comment by 66eli77** [comment]
step 9 solved the issue
