### ISSUE TITLE
setup error: No such file or directory ... data.sqlite

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/ka-lite#5035]
## Summary

Following the [getting started instructions](https://github.com/learningequality/ka-lite/wiki/Getting-started), running

    kalite manage setup --username=admin --password=pass --noinput

returns an error:

```
Traceback (most recent call last):
  File "/Users/d/Projects/learningequality/repos/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/d/Projects/learningequality/repos/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/learningequality/repos/ka-lite/kalite/distributed/management/commands/setup.py", line 379, in handle
    shutil.copy(settings.DB_TEMPLATE_DEFAULT, settings.DEFAULT_DATABASE_PATH)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/d/Projects/learningequality/repos/ka-lite/kalite/database/templates/data.sqlite'
```

## Branch or installer method

`develop` branch, OSX 10.9.5, Python 2.7.11

## How to reproduce

Check out a fresh copy of the `develop`, create a new virtualenv environment, and follow the [instructions](https://github.com/learningequality/ka-lite/wiki/Getting-started) until step 8.

## Initial Analysis

This seems to stem from [`kalite/distributed/management/commands/setup.py`](https://github.com/learningequality/ka-lite/blob/5c9200ac5225ae00061a62b6e3a79a1b30df771c/kalite/distributed/management/commands/setup.py#L377) which has the check `not database_exists` which should probably be `database_exists` on L377?

Changing this line lets the process proceed further, but then errors out further down the same file with:

```
Traceback (most recent call last):
  File "/Users/d/Projects/learningequality/repos/ka-lite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/d/Projects/learningequality/repos/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/learningequality/repos/ka-lite/kalite/distributed/management/commands/setup.py", line 390, in handle
    for file_name in os.listdir(settings.DB_CONTENT_ITEM_TEMPLATE_DIR):
OSError: [Errno 2] No such file or directory: '/Users/d/Projects/learningequality/repos/ka-lite/kalite/database/templates/content_items'
```

**Comment by indirectlylit** [comment]
I believe my change in 60dc95f28d02d1048d7752e69a8a38f7de90746a should have addressed this issue.

**Comment by indirectlylit** [comment]
@Kevsy - were you able to get beyond this issue? I'll close it if so

**Comment by Kevsy** [comment]
@indirectlylit yes sorry - my gh notifications were being blackholed by my mail server! all good now.

**Comment by indirectlylit** [comment]
thanks
