### ISSUE TITLE
String format error durring unpack_assessment_items

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5209]
## Summary

There's an error in our tests, which I don't know where's from or if harmless, better fix it though.

## Branch or installer method

 - Branch: 0.16.x

## Traceback or relevant snippet from server.log

```
...[INFO] [2016-07-13 02:49:11,623] kalite: Downloading assessment item data from a remote server. Please be patient; this file is big, so this may take some time...
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/home/ubuntu/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file unpack_assessment_zip.py, line 49
Downloading file....
```

This may be the related failure:

```

======================================================================
ERROR: test_command_with_url (kalite.contentload.tests.unpack_assessment_zip.UnpackAssessmentZipCommandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/ubuntu/ka-lite/kalite/contentload/tests/unpack_assessment_zip.py", line 78, in test_command_with_url
    force_download=True  # always force the download, so we can be sure the get method gets called
  File "/home/ubuntu/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/home/ubuntu/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/ka-lite/kalite/contentload/management/commands/unpack_assessment_zip.py", line 80, in handle
    call_command("annotate_content_items")
  File "/home/ubuntu/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/home/ubuntu/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/ka-lite/kalite/topic_tools/management/commands/annotate_content_items.py", line 43, in handle
    annotate_content_models(database_path=database_path, channel=channel, language=language)
  File "/home/ubuntu/ka-lite/kalite/topic_tools/content_models.py", line 128, in wrapper
    output = function(*args, **kwargs)
  File "/home/ubuntu/ka-lite/kalite/topic_tools/content_models.py", line 725, in annotate_content_models
    parents_to_update = new_parents_to_update
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3702, in __exit__
    return self._helper.__exit__(exc_type, exc_val, exc_tb)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3794, in __exit__
    exc_type, exc_val, exc_tb)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3768, in __exit__
    self.rollback()
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3757, in rollback
    self._execute('ROLLBACK TO SAVEPOINT %s;' % self.quoted_sid)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3751, in _execute
    self.db.execute_sql(query, require_commit=False)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: cannot rollback savepoint - SQL statements in progress
```

## How to reproduce

https://circleci.com/gh/learningequality/ka-lite/2400

**Comment by benjaoming** [comment]
Fixed in #5214
