### ISSUE TITLE
kalite manage retrievecontentpack local error

### ISSUE THREAD

**Issue by tim-moody** [learningequality/ka-lite#5265]
## Summary

kalite manage retrievecontentpack local ar ar.zip give error

## System information

 - Operating system: fedora 22
 - Version: 0.16.8
 - Browser:  command line

## Traceback or relevant snippet from server.log

 wget http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/ar.zip

[root@schoolserver kalite-langs]# kalite manage retrievecontentpack local ar ar.zip
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/kalite/distributed/management/commands/retrievecontentpack.py", line 70, in handle
    self.setup(options)
  File "/usr/lib/python2.7/site-packages/kalite/updates/management/commands/classes.py", line 55, in setup
    self.progress_log = UpdateProgressLog.get_active_log(process_name=self.process_name)
  File "/usr/lib/python2.7/site-packages/kalite/updates/models.py", line 168, in get_active_log
    if logs.count() > 0:
  File "/usr/share/kalite/python-packages/django/db/models/query.py", line 372, in count
    return self.query.get_count(using=self.db)
  File "/usr/share/kalite/python-packages/django/db/models/sql/query.py", line 423, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "/usr/share/kalite/python-packages/django/db/models/sql/query.py", line 389, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "/usr/share/kalite/python-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/kalite/python-packages/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/share/kalite/python-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
DatabaseError: no such table: updates_updateprogresslog

**Comment by tim-moody** [comment]
sorry the KALITE_HOME environment variable was not set
