### ISSUE TITLE
Video subtitle BDD test is unreliable

### ISSUE THREAD

**Issue by benjaoming** [learningequality/ka-lite#5288]
## Summary

Another messy BDD test.
## System information
- Operating system: Circle
## Traceback or relevant snippet from server.log

```


  @uses_video_with_subtitles
  Scenario: Subtitles are available when            # kalite/distributed/features/learn_content.feature:15
    When I visit a video with subtitles             # kalite/distributed/features/steps/learn_content.py:44
[INFO] [2016-09-20 17:22:13,489] django.request: HTTP Request /learn/khan/video_with_subtitles - Response: 200
[INFO] [2016-09-20 17:22:13,547] django.request: HTTP Request /_generated/dynamic.css - Response: 200
[INFO] [2016-09-20 17:22:13,696] django.request: HTTP Request /_generated/dynamic.js - Response: 200
[INFO] [2016-09-20 17:22:14,444] django.request: HTTP Request /securesync/api/user/status/ - Response: 200
[INFO] [2016-09-20 17:22:14,509] django.request: HTTP Request /api/topic_tree/khan - Response: 200
[INFO] [2016-09-20 17:22:14,731] django.request: HTTP Request /api/content/khan/video_with_subtitles/ - Response: 200
[WARNING] [2016-09-20 17:22:15,602] django.request: Not Found: /static/srt/en/subtitles/my_cool_id.vtt
[INFO] [2016-09-20 17:22:15,627] django.request: HTTP Request /static/srt/en/subtitles/my_cool_id.vtt - Response: 404
    When I visit a video with subtitles             # kalite/distributed/features/steps/learn_content.py:44 3.099s
    Then the video player is aware of the subtitles # kalite/distributed/features/steps/learn_content.py:50
    Then the video player is aware of the subtitles # kalite/distributed/features/steps/learn_content.py:50 0.123s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/learn_content.py", line 60, in impl
          text_tracks = context.browser.execute_script('return player.textTracks().length;')
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 403, in execute_script
          {'script': script, 'args':converted_args})['value']
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 175, in execute
          self.error_handler.check_response(response)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
          raise exception_class(message, screen, stacktrace)
      WebDriverException: Message: player.textTracks(...) is undefined
      Stacktrace:
          at anonymous (http://localhost:9000/learn/khan/video_with_subtitles/ line 69 > Function:1)
          at handleEvaluateEvent (http://localhost:9000/learn/khan/video_with_subtitles/:69)
```
## How to reproduce

Happes very rarely, but randomly

**Comment by benjaoming** [comment]
Not able to debug this, hasn't happened much lately.
