### ISSUE TITLE
kalite not starting on Ubuntu V 17.04

### ISSUE THREAD

**Issue by mrizwan65** [learningequality/ka-lite#5469]
## Summary

I downloaded  ka-lite-bundle_0.17.1-0ubuntu1_all.deb"  file and installed it as per the installation instruction for Ubuntu but when executing kalite start the following error is displayed: no such file or directory
I am running the command from my home directory.

## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Ubuntu 
 - Version: 17.04
 - Browser: Firefox

## Traceback or relevant snippet from server.log

CONGRATULATIONS! You've finished setting up the KA Lite server software.
You can now start KA Lite with the following command:

    kalite start

Do you wish to start the server now? (yes or no) yes
Running kalite start
Running 'kalite start' as daemon (system service)
Going to daemon mode, logging to /home/mr/.kalite/server.log

Traceback (most recent call last):
  File "/usr/bin/kalite", line 121, in <module>
    cli.main()
  File "/usr/lib/python2.7/dist-packages/kalite/cli.py", line 848, in main
    port=arguments["--port"]
  File "/usr/lib/python2.7/dist-packages/kalite/cli.py", line 498, in start
    print_server_address(port)
  File "/usr/lib/python2.7/dist-packages/kalite/cli.py", line 374, in print_server_address
    addresses = get_ip_addresses(include_loopback=False)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/bundled/fle_utils/internet/functions.py", line 108, in get_ip_addresses
    ips = [iface.get("inet") for iface in ifcfg.interfaces().values()]
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/__init__.py", line 60, in interfaces
    parser = get_parser()
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/__init__.py", line 44, in get_parser
    parser = LinuxParser(ifconfig=ifconfig)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/parser.py", line 159, in __init__
    super(LinuxParser, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/parser.py", line 141, in __init__
    super(UnixParser, self).__init__(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/parser.py", line 36, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/parser.py", line 54, in parse
    ifconfig, err, retcode = exec_cmd(self._meta.ifconfig_cmd_args)
  File "/usr/lib/python2.7/dist-packages/kalite/packages/dist/ifcfg/tools.py", line 20, in exec_cmd
    proc = Popen(cmd_args, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```
server.log is empty

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by benjaoming** [comment]
Hi @mrizwan65 

Thanks for reporting and for putting a nice and simple traceback, the issue is known and fixed already. It just hasn't been released, but it will in 0.17.2: http://ka-lite.readthedocs.io/en/0.17.x/installguide/release_notes.html#unreleased

A workaround is to install the missing `ifconfig` command, which you can do with `sudo apt install net-tools`
