### ISSUE TITLE
When ı try to register my device it showed up

### ISSUE THREAD

**Issue by topsecret98** [learningequality/ka-lite#5570]
## Summary

When I tried registering my device it showed up

## System information

 - Operating system: Windows 10
 - Version: 0.17.4
 - Browser: Chrome/Edge

## Traceback or relevant snippet from server.log

```
URL: /securesync/register/
querystring: <QueryDict: {}>
ValidationError: [u'Could not verify the imported model.']

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\django\core\handlers\base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\securesync\devices\views.py", line 31, in register_public_key
    return register_public_key_client(request)
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\django\contrib\auth\decorators.py", line 25, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\kalite\packages\dist\annoying\decorators.py", line 92, in wrapper
    output = function(request, *args, **kwargs)
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\securesync\devices\views.py", line 61, in register_public_key_client
    reg_response = client.register()
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\securesync\devices\api_client.py", line 59, in register
    model.object.save(imported=True, increment_counters=False)
  File "C:\Python27\lib\site-packages\kalite\packages\bundled\securesync\engine\models.py", line 351, in save
    raise ValidationError("Could not verify the imported model.")  #Imported model's signature did not match.")
ValidationError: [u'Could not verify the imported model.']




## Screenshots

![image](https://user-images.githubusercontent.com/37200229/38679376-41a057e6-3e6c-11e8-9a12-c7b452a6c3c4.png)

![image](https://user-images.githubusercontent.com/37200229/38679436-6de06bac-3e6c-11e8-930c-4ef8977c432e.png)

**Comment by benjaoming** [comment]
Hi @topsecret98 - I don't know if a temporary network issue could be the cause of this. Has the error been persistent?
